taycet_items = [
    0x0B0, # "SpicySoup",
    0x0B1, # "ApplePie",
    0x0B2, # "HoneyUltra",
    0x0B3, # "MapleUltra",
    0x0B4, # "JellyUltra",
    #0x0B5, # "Koopasta",
    0x0B6, # "FriedShroom",
    0x0B7, # "ShroomCake",
    0x0B8, # "ShroomSteak",
    0x0B9, # "HotShroom",
    0x0BA, # "SweetShroom",
    0x0BB, # "YummyMeal",
    0x0BC, # "HealthyJuice",
    0x0BD, # "BlandMeal",
    0x0BE, # "DeluxeFeast",
    0x0BF, # "SpecialShake",
    0x0C0, # "BigCookie",
    #0x0C1, # "Cake",
    #0x0C2, # "Mistake",
    #0x0C3, # "KoopaTea",
    0x0C4, # "HoneySuper",
    0x0C5, # "MapleSuper",
    0x0C6, # "JellySuper",
    0x0C7, # "Spaghetti",
    0x0C8, # "EggMissile",
    0x0C9, # "FriedEgg",
    0x0CA, # "HoneyShroom",
    0x0CB, # "HoneyCandy",
    0x0CC, # "ElectroPop",
    0x0CD, # "FirePop",
    0x0CE, # "LimeCandy",
    0x0CF, # "CocoPop",
    0x0D1, # "JellyPop",
    0x0D2, # "StrangeCake",
    #0x0D3, # "KookyCookie",
    0x0D4, # "FrozenFries",
    0x0D5, # "PotatoSalad",
    #0x0D6, # "NuttyCake",
    0x0D7, # "MapleShroom",
    0x0D8, # "BoiledEgg",
    0x0D9, # "YoshiCookie",
    0x0DA, # JellyShroom1
]

unused_items = [
    "InsecticideHerb",
    "HustleDrink",
    "SmashCharge0",
    "JumpCharge0",
    "Berserker",
    "RightOn",
    "AutoJump",
    "AutoSmash",
    "CrazyHeart",
    "MegaHPDrain",
    "AutoMultibounce",
    "FlowerFanatic",
    "SuperJump",
    "SuperSmash",
    "SuperFocus",
    "EarthquakeJump",
    "HappyHeartX",
    "FlowerSaverX",
    "DamageDodgeX",
    "PowerPlusX",
    "DefendPlusX",
    "DefendPlusY",
    "HappyFlowerX",
    "AttackFXF",
    "HPPlusX",
    "HPPlusY",
    "FPPlusX",
    "FPPlusY",
    "HealthyHealthy",
    "ShrinkSmash"
]

unplaceable_items = [
    "LuckyStar",
    "HomewardShroom",
    "BigMap",
    "KoopaFortressKey",
    "RuinsKey",
    "TubbaCastleKey",
    "BowserCastleKey",
    "ForestPass",
    "MysticalKey",
    "SuspiciousNote",
    "Screwdriver",
    "ToadDoll",
    "UnusedLetter01",
    "UnusedLetter02",
    "UnusedLetter03",
    "UnusedLetter04",
    "UnusedLetter05",
    "UnusedLetter06",
    "UnusedLetter07",
    "BakingSugar",
    "BakingSalt",
    "BakingEgg",
    "BakingCream",
    "BakingStrawberry",
    "BakingButter",
    "BakingCleanser",
    "BakingWater",
    "BakingFlour",
    "BakingMilk",
    "PeachKey1",
    "SneakyParasol",
    "KootShell",
    "KootAltPhoto",
    "PeachKey2",
    "PrisonKey1",
    "PrisonKey2",
    "PrisonKey3",
    "PrisonKey4",
    "PleaseComeBack",
    "JellyShroom2",
    "JellyShroom3",
    "JellyShroom4",
    "JellyShroom5",
    "JellyShroom6",
    "MysteryScroll",
    "PowerSmash2",
    "PowerSmash3",
    "ShellCrack",
    "Kaiden",
    "AttackFXF2",
    "AttackFXF3",
    "AttackFXF4",
    "AttackFXF5",
    "PartnerAttack",
    "Heart",
    "HeartPiece",
    "StarPoint",
    "HeartPoint",
    "FlowerPoint",
    "StarPiece",
    "Present",
    "CakeDone",
    "CakeBare",
    "CakePan",
    "CakeBatter",
    "CakeBowl",
    "CakeMixed",
    "CakeWithIcing",
    "CakeWithBerries",
    "Hammer1Icon",
    "Hammer2Icon",
    "Hammer3Icon",
    "Boots1Icon",
    "Boots2Icon",
    "Boots3Icon",
    "ItemsIcon",
    "CakeKey",
    "BlueBerryKey1",
    "BlueBerryKey2",
    "RedBerryKey",
    "YellowBerryKey",
    "BubbleBerryKey",
    "Goompa"
]
