verbose_item_locations = {
# Goomba Region
    "KMR_00": {"HiddenPanel": "Hidden Panel",},
    "KMR_02": {"GiftA": "Goompa Koopa Koot Favor",
               "GiftB": "Goompa Gift",
               "GiftC": "Goombaria Dolly Reward",
               "GiftD": "Goompa Letter Reward",
               "GiftE": "Goompapa Letter Reward 1",
               "GiftF": "Goompapa Letter Reward 2",
               "ItemA": "On The Balcony",
               "Tree1_Drop1A": "Goomnut Tree",
               "Partner": "Goombario Partner",
               "Bush2_Drop1": "Bush Bottom Right"},
    "KMR_03": {"ItemA": "Floating Coin 1",
               "ItemB": "Floating Coin 2",
               "ItemC": "Floating Coin 3",
               "ItemD": "Floating Coin 4",
               "ItemE": "Upper Ledge",
               "Tree1_Drop1A": "In Tree",
               "HiddenPanel": "Hidden Panel",
               "YBlockA": "Block On Ground",
               "HiddenYBlockA": "Above Stone Block",},
    "KMR_04": {"Tree3_Drop1A": "In Tree Right",
               "Bush1_Drop1": "Bush Right",
               "Bush2_Drop1": "Bush Bottom Right",
               "Bush3_Drop1A": "Bush Top 1",
               "Bush3_Drop1B": "Bush Top 2",
               "Bush4_Drop1": "Bush Center",
               "Bush5_Drop1": "Bush Top Left",
               "Tree1_Drop1": "In Tree Left",
               "Tree2_Drop1": "In Tree Top",
               "Bush7_Drop1": "In Hammer Bush",
               "RandomBlockItemA": "In MultiCoinBlock"},
    "KMR_05": {"ItemA": "On Ledge",
               "Tree1_Drop1A": "In Tree"},
    "KMR_06": {"ItemA": "On the Sign",
               "RBlockA": "Red Block",},
    "KMR_09": {"YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},
    "KMR_10": {"ChestA": "Chest On Roof",
               "YBlockA": "Yellow Block",},
    "KMR_11": {"HiddenPanel": "Hidden Panel",
               "Tree1_Drop1A": "In Tree Left Of Fortress",
               "Tree2_Drop1": "In Tree Right Of Cliff",
               "YBlockA": "Hidden Yellow Block",},
    "KMR_20": {"GiftA": "Luigi Koopa Koot Favor",},

# Toad Town
    "MAC_00": {"ItemA": "Sushie Island",
               "GiftA": "Russ T. Dictionary Reward",
               "GiftB": "Russ T. Letter Reward",
               "GiftC": "Miss T. Letter Reward",
               "GiftD": "Radio Trade Event 1 Reward",
               "HiddenPanel": "Hidden Panel",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",
               "DojoA": "Dojo: Chan",
               "DojoB": "Dojo: Lee",
               "DojoC": "Dojo: Master 1",
               "DojoD": "Dojo: Master 2",
               "DojoE": "Dojo: Master 3",},
    "MAC_01": {"ItemA": "Merlon House Stomping",
               "GiftA": "Rowf's Calculator Reward",
               "GiftB": "Postmaster MailBag Reward",
               "GiftC": "Merlon Letter Reward",
               "GiftD": "Minh T. Letter Reward",
               "Tree1_Drop1A": "In Tree",
               "ShopBadgeA": "Rowf's Shop Set 1 - 1",
               "ShopBadgeB": "Rowf's Shop Set 1 - 2",
               "ShopBadgeC": "Rowf's Shop Set 1 - 3",
               "ShopBadgeD": "Rowf's Shop Set 1 - 4",
               "ShopBadgeE": "Rowf's Shop Set 2 - 1",
               "ShopBadgeF": "Rowf's Shop Set 2 - 2",
               "ShopBadgeG": "Rowf's Shop Set 2 - 3",
               "ShopBadgeH": "Rowf's Shop Set 3 - 1",
               "ShopBadgeI": "Rowf's Shop Set 3 - 2",
               "ShopBadgeJ": "Rowf's Shop Set 3 - 3",
               "ShopBadgeK": "Rowf's Shop Set 4 - 1",
               "ShopBadgeL": "Rowf's Shop Set 4 - 2",
               "ShopBadgeM": "Rowf's Shop Set 4 - 3",
               "ShopBadgeN": "Rowf's Shop Set 5 - 1",
               "ShopBadgeO": "Rowf's Shop Set 5 - 2",
               "ShopBadgeP": "Rowf's Shop Set 5 - 3",},
    "MAC_02": {"GiftA": "Bub-ulb Gift",
               "GiftB": "Tayce T. Frying Pan Reward",
               "GiftC": "Fice T. Letter Reward",
               "GiftD": "Fice T. Forest Pass",
               "ItemA": "Inside Blue House",
               "HiddenPanel": "Hidden Panel",},
    "MAC_03": {"GiftA": "Dane T. Letter Reward 1",
               "GiftB": "Dane T. Letter Reward 2",
               "HiddenPanel": "Hidden Panel",},
    "MAC_04": {"ItemA": "Storeroom Item 1",
               "ItemB": "Storeroom Item 2",
               "ItemC": "Storeroom Item 3",
               "ItemD": "Storeroom Item 4",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "MAC_05": {"GiftA": "Poet Gift",
               "GiftB": "Poet Melody Reward",
               "GiftC": "Fishmael Letter Reward",
               "GiftD": "Radio Trade Event 3 Reward",
               "HiddenPanel": "Hidden Panel",
               "RandomBlockItemA": "In MultiCoinBlock"},

# Toad Town Tunnels
    "TIK_02": {"ChestA": "Blooper Fight Reward"},
    "TIK_03": {"YBlockA": "Yellow Block Center",
               "YBlockB": "Yellow Block Left",
               "YBlockC": "Yellow Block Right",},
    "TIK_05": {"ChestA": "Chest On Ledge"},
    "TIK_07": {"ItemA": "On Parakarry Ledge",
               "RandomBlockItemA": "In SuperBlock"},
    "TIK_10": {"HiddenYBlockA": "Hidden Block Left",
               "HiddenYBlockB": "Hidden Block Center",
               "HiddenYBlockC": "Hidden Block Right",
               "RandomBlockItemA": "In SuperBlock",},
    "TIK_12": {"RandomBlockItemA": "In SuperBlock"},
    "TIK_15": {"GiftA": "Rip Cheato Offer 1",
               "GiftB": "Rip Cheato Offer 2",
               "GiftC": "Rip Cheato Offer 3",
               "GiftD": "Rip Cheato Offer 4",
               "GiftE": "Rip Cheato Offer 5",
               "GiftF": "Rip Cheato Offer 6",
               "GiftG": "Rip Cheato Offer 7",
               "GiftH": "Rip Cheato Offer 8",
               "GiftI": "Rip Cheato Offer 9",
               "GiftJ": "Rip Cheato Offer 10",
               "GiftK": "Rip Cheato Offer 11",},
    "TIK_17": {"RandomBlockItemA": "In SuperBlock"},
    "TIK_18": {"HiddenYBlockA": "Hidden Block",
               "RandomBlockItemA": "In MultiCoinBlock"},
    "TIK_19": {"RandomBlockItemA": "In SuperBlock"},
    "TIK_20": {"YBlockA": "Yellow Block"},
    "TIK_21": {"YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "YBlockC": "Yellow Block 3",
               "YBlockD": "Yellow Block 4",
               "YBlockE": "Yellow Block 5",},
    "TIK_23": {"HiddenYBlockA": "Hidden Block Center",
               "HiddenYBlockB": "Hidden Block Right",
               "HiddenYBlockC": "Hidden Block Left",
               "YBlockA": "Yellow Block",},
    "TIK_24": {"HiddenYBlockA": "Hidden Block",
               "YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},
    "TIK_25": {"BigChest": "In Big Chest",},

# Peach's Castle
    "KKJ_16": {"ItemA": "Upper Level",
               "ItemB": "Between Bookshelves",},
    "KKJ_17": {"ItemA": "On The Ground"},
    "KKJ_20": {"ChestA": "In Chest"},

# Shooting Star Summit
    "HOS_00": {"HiddenPanel": "Hidden Panel",},
    "HOS_01": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Behind The Summit",},
    "HOS_03": {"ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "HOS_06": {"GiftA": "Merluvlee Koopa Koot Favor",
               "GiftB": "Merlow Letter Reward",
               "HiddenPanel": "Hidden Panel",
               "ShopBadgeA": "Merlow's Badges 1",
               "ShopBadgeB": "Merlow's Badges 2",
               "ShopBadgeC": "Merlow's Badges 3",
               "ShopBadgeD": "Merlow's Badges 4",
               "ShopBadgeE": "Merlow's Badges 5",
               "ShopBadgeF": "Merlow's Badges 6",
               "ShopBadgeG": "Merlow's Badges 7",
               "ShopBadgeH": "Merlow's Badges 8",
               "ShopBadgeI": "Merlow's Badges 9",
               "ShopBadgeJ": "Merlow's Badges 10",
               "ShopBadgeK": "Merlow's Badges 11",
               "ShopBadgeL": "Merlow's Badges 12",
               "ShopBadgeM": "Merlow's Badges 13",
               "ShopBadgeN": "Merlow's Badges 14",
               "ShopBadgeO": "Merlow's Badges 15",
               "ShopRewardA": "Merlow's Rewards 1",
               "ShopRewardB": "Merlow's Rewards 2",
               "ShopRewardC": "Merlow's Rewards 3",
               "ShopRewardD": "Merlow's Rewards 4",
               "ShopRewardE": "Merlow's Rewards 5",
               "ShopRewardF": "Merlow's Rewards 6",},

# Koopa Region
    "NOK_01": {"Bush1_Drop1A": "Bush Far Left",
               "Bush3_Drop1A": "Bush Left Front",
               "Bush4_Drop1A": "Bush Infront Of Tree",
               "Bush5_Drop1A": "Bush Second From Right",
               "Bush6A_Drop1A": "Bush Second From Left (Koopa Koot Favor)",
               "Bush7A_Drop1A": "Bush Far Right (Koopa Koot Favor)",
               "GiftA": "Mort T. Letter Reward",
               "GiftB": "Koover Letter Reward 1",
               "GiftC": "Koover Letter Reward 2",
               "HiddenPanel": "Hidden Panel",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "NOK_02": {"Bush1_Drop1": "Bush Far Left",
               "Bush6_Drop1": "Bush Far Right",
               "GiftA": "Kolorado's Wife (Koopa Koot Favor)",
               "GiftB": "Koopa Koot Silver Credit",
               "GiftC": "Koopa Koot Gold Credit",
               "GiftD": "Kolorado Artifact Reward",
               "GiftE": "Kolorado Letter Reward",
               "ItemA": "Push Block Puzzle",
               "Partner": "Kooper Partner",
               "KootGift00": "Koopa Koot Reward 1",
               "KootGift01": "Koopa Koot Reward 2",
               "KootGift02": "Koopa Koot Reward 3",
               "KootGift03": "Koopa Koot Reward 4",
               "KootGift04": "Koopa Koot Reward 5",
               "KootGift05": "Koopa Koot Reward 6",
               "KootGift06": "Koopa Koot Reward 7",
               "KootGift07": "Koopa Koot Reward 8",
               "KootGift08": "Koopa Koot Reward 9",
               "KootGift09": "Koopa Koot Reward 10",
               "KootGift0A": "Koopa Koot Reward 11",
               "KootGift0B": "Koopa Koot Reward 12",
               "KootGift0C": "Koopa Koot Reward 13",
               "KootGift0D": "Koopa Koot Reward 14",
               "KootGift0E": "Koopa Koot Reward 15",
               "KootGift0F": "Koopa Koot Reward 16",
               "KootGift10": "Koopa Koot Reward 17",
               "KootGift11": "Koopa Koot Reward 18",
               "KootGift12": "Koopa Koot Reward 19",
               "KootGift13": "Koopa Koot Reward 20",},
    "NOK_03": {"ItemA": "On Stump",},
    "NOK_04": {"GiftA": "Fuzzy Battle Reward",},
    "NOK_11": {"RBlockA": "Red Block Center",
               "YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},
    "NOK_12": {"ItemA": "Kooper Island",
               "ItemB": "Behind Fence",
               "YBlockA": "Yellow Block",
               "RandomBlockItemA": "In MultiCoinBlock",},
    "NOK_13": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Behind Peg",
               "RBlockA": "Brick Block Puzzle",},
    "NOK_14": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",
               "ItemA": "X On Ground 1",
               "ItemB": "X On Ground 2",
               "ItemC": "X On Ground 3",
               "ItemD": "X On Ground 4",
               "ItemE": "X On Ground 5",
               "ItemF": "On Brick Block",},
    "NOK_15": {"Tree1_Drop1A": "In Tree",},

# Koopa Bros. Fortress
    "TRD_00": {"ChestA": "Chest Behind Fortress",
               "ChestB": "Chest On Ledge",},
    "TRD_01": {"ItemA": "Top Of Tower",
               "ItemB": "Koopa Troopa Reward",},
    "TRD_03": {"ItemA": "Left Cell",
               "ItemB": "Right Cell",
               "ItemC": "Center Cell",},
    "TRD_06": {"Partner": "Bombette Partner"},
    "TRD_08": {"ItemA": "On The Ground",},
    "TRD_09": {"YBlockA": "Block Behind Rock",},

# Mt Rugged
    "IWA_00": {"ItemA": "On Slide 1",
               "ItemB": "On Slide 2",
               "ItemC": "On Slide 3",
               "ItemD": "Hurting Whacka",
               "YBlockA": "Yellow Block",},
    "IWA_01": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Parakarry Ledge",
               "ItemB": "Kooper Ledge",},
    "IWA_02": {"GiftA": "Bub-ulb Gift",
               "ItemA": "On Scaffolding",},
    "IWA_03": {"ChestA": "Hidden Cave Chest",
               "ItemA": "Slide Ledge",
               "ItemB": "Left Ledge Center",
               "ItemC": "Left Ledge Right",
               "ItemD": "Left Ledge 3",
               "ItemE": "Left Ledge 4",
               "ItemF": "Left Ledge 5",
               "ItemG": "Left Ledge 6",
               "ItemH": "Left Ledge 7",
               "ItemI": "Bottom Left 1",
               "ItemJ": "Bottom Left 2",
               "YBlockA": "Yellow Block Top Left",
               "YBlockB": "Yellow Block Floating",
               "YBlockC": "Yellow Block Top Right",},
    "IWA_04": {"ItemA": "Bottom Of Cliff",},
    "IWA_10": {"Bush1_Drop1": "Bush 1",
               "Bush2_Drop1": "Bush 2",
               "Bush3_Drop1": "Bush 3",
               "Bush4_Drop1": "Bush Top",
               "Partner": "Parakarry Partner",
               "RandomBlockItemA": "In SuperBlock",},

# Dry Dry Outpost
    "DRO_01": {"GiftA": "Composer Lyrics Reward",
               "GiftB": "Store Legend",
               "GiftC": "Little Mouser Letter Reward",
               "Tree1_Drop1": "In Red Tree",
               "ShopItemA": "Shop Item 1",
               "ShopItemC": "Shop Item 3",
               "ShopItemF": "Shop Item 6",},
    "DRO_02": {"GiftA": "Merlee Request (Koopa Koot Favor)",
               "GiftB": "Moustafa Gift",
               "GiftC": "Mr. E. Letter Reward",
               "HiddenPanel": "Hidden Panel",
               "ItemA": "Toad House Roof",},

# Dry Dry Desert
    "SBK_00": {"YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},
    "SBK_02": {"GiftA": "Radio Trade Event 2 Reward",},
    "SBK_05": {"ItemA": "Behind Cactus",},
    "SBK_06": {"Tree1_Drop1": "In Tree",
               "RandomBlockItemA": "In MultiCoinBlock"},
    "SBK_10": {"HiddenYBlockA": "Hidden Block",},
    "SBK_14": {"YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",
               "RandomBlockItemA": "In MultiCoinBlock",},
    "SBK_20": {"YBlockA": "Hit Block",
               "YBlockB": "Hit Block Plenty",
               "YBlockC": "Hit Block Very Much",},
    "SBK_22": {"YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "YBlockC": "Yellow Block 3",
               "YBlockD": "Yellow Block 4",
               "YBlockE": "Yellow Block Center",},
    "SBK_24": {"HiddenRBlockA": "Hidden Block",},
    "SBK_25": {"RandomBlockItemA": "In MultiCoinBlock Center",
               "RandomBlockItemB": "In MultiCoinBlock Bottom Right",},
    "SBK_26": {"Tree1_Drop1": "In Tree",},
    "SBK_30": {"Tree2_Drop1A": "In Tree",},
    "SBK_33": {"HiddenPanel": "Hidden Panel",},
    "SBK_34": {"GiftA": "Nomadimouse Letter Reward",
               "Tree1_Drop1": "In Tree",},
    "SBK_35": {"Tree1_Drop1": "In Tree Far Left",},
    "SBK_36": {"Tree9_Drop1A": "In Tree (Far Right)",
               "Tree1_Drop1": "In Tree (Far Left)",
               "Tree2_Drop1": "In Tree (Second From Left)",
               "Tree6_Drop1": "In Tree (Fourth From Right)",},
    "SBK_40": {"RandomBlockItemA": "In MultiCoinBlock Top Left",},
    "SBK_43": {"YBlockA": "Yellow Block",},
    "SBK_45": {"ItemA": "On Brick Block",
               "ItemB": "Ontop Of Bluffs",},
    "SBK_46": {"HiddenYBlockA": "Hidden Block",
               "YBlockA": "Yellow Block",
               "Tree2_Drop1": "Tree Bottom Left",},
    "SBK_52": {"RandomBlockItemA": "In MultiCoinBlock Top",},
    "SBK_55": {"ItemA": "Behind Bush",
               "Tree1_Drop1": "In Tree",
               "RandomBlockItemA": "In MultiCoinBlock",},
    "SBK_56": {"Tree1_Drop1A": "In Fruit Tree (Left)",
               "Tree2_Drop1A": "In Fruit Tree (Right)",
               "Tree3_Drop1": "In Tree (Far Left)",
               "Tree9_Drop1": "In Tree (Front Right)",
               "RandomBlockItemA": "In SuperBlock",},
    "SBK_61": {"HiddenRBlockA": "Hidden Block",},
    "SBK_64": {"YBlockA": "Yellow Block",},
    "SBK_66": {"Tree3_Drop1": "In Tree (Far Right)",
               "RandomBlockItemA": "In MultiCoinBlock Top Left",
               "RandomBlockItemB": "In MultiCoinBlock Top Right",
               "RandomBlockItemC": "In MultiCoinBlock Right",
               "RandomBlockItemD": "In MultiCoinBlock Left",
               "RandomBlockItemE": "In MultiCoinBlock Bottom Left",
               "RandomBlockItemF": "In MultiCoinBlock Bottom Right",},

# Dry Dry Ruins
    "ISK_02": {"ItemA": "In Sarcophagus",},
    "ISK_03": {"ItemA": "On The Ground",},
    "ISK_05": {"ItemA": "On Pedestal",},
    "ISK_06": {"ItemA": "In The Sand",
               "ItemB": "On Ledge",},
    "ISK_07": {"ItemA": "Pokey Gauntlet Reward",
               "ItemB": "Behind Hammer Block",},
    "ISK_09": {"ChestA": "Hidden Chest",
               "BigChest": "In Big Chest",},
    "ISK_10": {"RandomBlockItemA": "In SuperBlock",},
    "ISK_12": {"ItemA": "On Ledge",},
    "ISK_13": {"ItemA": "On Pedestal",},
    "ISK_14": {"ItemA": "On Pedestal",},

# Forever Forest
    "MIM_04": {"GiftA": "Bub-ulb Gift",},
    "MIM_08": {"RBlockA": "Central Block",},
    "MIM_09": {"RBlockA": "Central Block",},
    "MIM_11": {"Bush1_Drop1": "In Bush (Back Right)",
               "YBlockA": "Yellow Block",},
    "MIM_12": {"HiddenPanel": "Hidden Panel",},

# Boo's Mansion
    "OBK_01": {"GiftA": "From Franky (Koopa Koot Favor)",
               "GiftB": "Franky Letter Reward",
               "HiddenPanel": "Hidden Panel",},
    "OBK_02": {"HiddenPanel": "Hidden Panel",},
    "OBK_03": {"CrateA": "In Crate",
               "GiftA": "Igor Letter Reward",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "OBK_04": {"CrateA": "In Crate",
               "BigChest": "In Big Chest",
               "HiddenPanel": "Hidden Panel",},
    "OBK_05": {"CrateA": "In Crate 1",
               "CrateB": "In Crate 2",},
    "OBK_06": {"CrateA": "In Crate",
               "ItemA": "On Bookshelf",},
    "OBK_07": {"ChestA": "In Chest",},
    "OBK_08": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Beat Boo Game",},
    "OBK_09": {"Partner": "Bow Partner"},

# Gusty Gulch
    "ARN_02": {"ItemA": "On Rock",
               "ItemB": "Infront Of Branch",
               "YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "YBlockC": "Yellow Block Right",},
    "ARN_03": {"GiftA": "From Boo (Koopa Koot Favor)",
               "YBlockA": "Yellow Block In House",},
    "ARN_04": {"ItemA": "Behind Rock",
               "YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",
               "RandomBlockItemA": "In MultiCoinBlock",},

# Tubba's Castle
    "DGB_03": {"ItemA": "On Table",},
    "DGB_04": {"RandomBlockItemA": "In SuperBlock",},
    "DGB_06": {"ChestA": "In Chest",},
    "DGB_07": {"ItemA": "On Table",},
    "DGB_11": {"ItemA": "On Table",},
    "DGB_12": {"ChestA": "In Chest",},
    "DGB_13": {"ItemA": "In Hidden Room",
               "ItemB": "On Bed 1",
               "ItemC": "On Bed 2",
               "ItemD": "On Bed 3",
               "ItemE": "On Bed 4",
               "ItemF": "On Bed 5",
               "ItemG": "On Bed 6",},
    "DGB_14": {"YBlockA": "Yellow Block",},
    "DGB_16": {"ItemA": "On Pedestal",},

# Shy Guy's Toybox
    "OMO_01": {"HiddenYBlockA": "Hidden Block 1",
               "HiddenYBlockB": "Hidden Block 2",
               "ItemA": "Calculator Thief 1",
               "ItemB": "Calculator Thief 2",
               "ItemC": "Shy Guy 2",
               "ItemD": "Shy Guy 3",
               "ItemE": "Shy Guy 4",
               "ItemF": "Shy Guy 5",},
    "OMO_02": {"HiddenYBlockA": "Hidden Block Left",
               "ItemA": "On Brick Block",
               "YBlockA": "Yellow Block Right",},
    "OMO_03": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",},
    "OMO_04": {"ChestA": "In Chest",
               "ItemA": "Infront Of Chest",
               "ItemB": "Midair 1",
               "ItemC": "Midair 2",
               "ItemD": "Midair 3",
               "ItemE": "Midair 4",
               "ItemF": "Midair 5",
               "ItemG": "Midair 6",
               "ItemH": "Midair 7",
               "ItemI": "Midair 8",
               "ItemJ": "On Building",
               "ItemK": "Behind Building Block",
               "YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "YBlockC": "Yellow Block On Ledge",},
    "OMO_05": {"HiddenYBlockA": "Hidden Block Right",
               "HiddenYBlockB": "Hidden Block Left",
               "ItemA": "Gourmet Guy Reward",
               "YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",},
    "OMO_06": {"ChestA": "In Chest",
               "HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",},
    "OMO_07": {"ChestA": "In Chest (Far Right)",
               "ChestB": "In Chest (Top Left)",
               "ChestC": "In Chest (Right)",
               "ItemA": "Infront Of Chest (Right)",
               "YBlockA": "Yellow Block",},
    "OMO_08": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",},
    "OMO_09": {"ChestA": "In Chest",
               "ItemA": "Infront Of Chest",
               "ItemB": "On Treadmill 1",
               "ItemC": "On Treadmill 2",
               "ItemD": "On Treadmill 3",
               "ItemE": "On Treadmill 4",
               "ItemF": "On Treadmill 5",
               "ItemG": "On Treadmill 6",
               "ItemH": "Hidden Room Center",
               "ItemI": "Hidden Room 1",
               "ItemJ": "Hidden Room 2",
               "ItemK": "Hidden Room 3",
               "ItemL": "Hidden Room 4",
               "ItemM": "Hidden Room 5",
               "ItemN": "Hidden Room 6",
               "ItemO": "Defeat Shy Guy",
               "RandomBlockItemA": "In MultiCoinBlock"},
    "OMO_10": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",},
    "OMO_11": {"HiddenRBlockA": "Hidden Block Center",
               "HiddenYBlockA": "Hidden Block Right",
               "HiddenYBlockB": "Hidden Block Left",
               "YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "RandomBlockItemA": "In SuperBlock",
               "RandomBlockItemB": "In MultiCoinBlock",},
    "OMO_12": {"Partner": "Watt Partner"},
    "OMO_13": {"ChestA": "In Chest",
               "HiddenYBlockA": "Hidden Block",
               "YBlockA": "Yellow Block",},
    "OMO_17": {"YBlockA": "Yellow Block South",
               "YBlockB": "Yellow Block North 1",
               "YBlockC": "Yellow Block North 2",
               "RandomBlockItemA": "In MultiCoinBlock",},

# Jade Jungle
    "JAN_00": {"ItemA": "Over Flower 1",
               "ItemB": "Over Flower 2",
               "ItemC": "Behind Bush",
               "Tree1_Drop1A": "In Palm Tree",},
    "JAN_01": {"HiddenYBlockA": "Hidden Block Left",
               "HiddenYBlockB": "Hidden Block Right",
               "ItemA": "On The Rocks",
               "ItemB": "Over Flower 1",
               "ItemC": "Over Flower 2",
               "Tree2_Drop1": "In Palm Tree 1",
               "Tree3_Drop1": "In Palm Tree 2",
               "Tree4_Drop1": "In Palm Tree 3",
               "Tree5_Drop1": "In Palm Tree 4",
               "Tree6_Drop1": "In Palm Tree 5",
               "Tree7_Drop1A": "In Palm Tree 6",
               "Tree7_Drop1B": "In Palm Tree 6 2",},
    "JAN_02": {"GiftA": "Village Leader Reward",
               "HiddenPanel": "Hidden Panel",
               "Tree2_Drop1A": "In Palm Tree Left",
               "Tree3_Drop1A": "In Palm Tree Right",},
    "JAN_03": {"GiftA": "Kolorado Volcano Vase Reward",
               "GiftB": "Yellow Yoshi Food Reward",
               "GiftC": "Red Yoshi Kid Letter Reward",
               "Tree1_Drop1A": "In Palm Tree",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "JAN_04": {"ChestA": "In Volcano Chest",
               "ItemA": "On Island",
               "Tree2_Drop1A": "In Island Tree",
               "Partner": "Sushie Partner",},
    "JAN_05": {"RBlockA": "Red Block",
               "Bush1_Drop1": "Bush (Bottom Right)",
               "Bush2_Drop1": "Bush (Bottom Left)",
               "Tree2_Drop1": "In Tree (Right)",},
    "JAN_06": {"ItemA": "Underwater",
               "Tree1_Drop1": "In Tree (Top Left)",},
    "JAN_07": {"Tree1_Drop1": "In Tree",},
    "JAN_08": {"HiddenYBlockA": "Hidden Block",
               "ItemA": "Underwater 1",
               "ItemB": "Underwater 2",
               "ItemC": "Underwater 3",
               "Bush1_Drop1": "Bush (Top Right)",
               "Bush2_Drop1": "Bush (Bottom Left)",
               "Tree2_Drop1": "In Tree (Top)",
               "Tree3_Drop1": "In Tree (Right)",
               "RandomBlockItemA": "In SuperBlock",},
    "JAN_09": {"Bush1_Drop1": "Bush 1",
               "Bush6_Drop1": "Bush 2",
               "Tree2_Drop1": "In Tree On Ledge",
               "Tree3_Drop1": "In Tree Right",},
    "JAN_10": {"ItemA": "Underwater",},
    "JAN_12": {"HiddenYBlockA": "Hidden Block",
               "Tree1_Drop1": "In Tree (Vine)",
               "Tree1_Drop2": "In Tree (Hit)",},
    "JAN_13": {"HiddenYBlockA": "Hidden Block",
               "Tree1_Drop1": "In Tree (Left)",},
    "JAN_14": {"Tree2_Drop1": "Tree Vine Second Left",
               "Tree5_Drop1": "Tree Vine Far Right",},
    "JAN_15": {"HiddenPanel": "Hidden Panel",
               "Tree2_Drop1": "In Tree (Right)",},
    "JAN_18": {"ItemA": "End Of Vine",},
    "JAN_22": {"GiftA": "Raphael Gift",
               "ItemA": "Behind Tree",},

# Mt Lavalava
    "KZN_03": {"ItemA": "On Stone Pillar",
               "ItemB": "On Brick Block",
               "YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "YBlockC": "Yellow Block 3",
               "YBlockD": "Yellow Block 4",},
    "KZN_04": {"RandomBlockItemA": "In SuperBlock",},
    "KZN_06": {"HiddenYBlockA": "Hidden Block",},
    "KZN_07": {"BigChest": "In Big Chest",},
    "KZN_08": {"ChestA": "In Chest",},
    "KZN_09": {"HiddenPanel": "Hidden Panel",
               "RandomBlockItemA": "In SuperBlock",},
    "KZN_18": {"HiddenPanel": "Hidden Panel",},
    "KZN_19": {"YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},

# Flower Fields
    "FLO_03": {"GiftA": "Petunia Gift",
               "HiddenPanel": "Hidden Panel",
               "Tree1_Drop1A": "In Tree 1",
               "Tree1_Drop1B": "In Tree 2",},
    "FLO_07": {"GiftA": "Posie Gift 1",
               "ItemA": "Posie Gift 2",},
    "FLO_08": {"ItemA": "In The Flowers",
               "ItemB": "Left Side Vine",
               "Tree1_Drop1A": "In Tree 1",
               "Tree1_Drop1B": "In Tree 2",
               "RandomBlockItemA": "In SuperBlock",},
    "FLO_09": {"Tree1_Drop1": "Tree Puzzle Reward",
               "ItemA": "Leftmost Vine",},
    "FLO_10": {"GiftA": "Lily Reward For WaterStone",
               "Tree1_Drop1A": "In Tree",},
    "FLO_11": {"RandomBlockItemA": "In MultiCoinBlock",},
    "FLO_12": {"GiftA": "Rosie Gift",},
    "FLO_13": {"ItemA": "Cage Under Rock",
               "ItemB": "In The Flowers",
               "Partner": "Lakilester Partner",},
    "FLO_14": {"ItemA": "On Ledge",
               "ItemB": "Right Vine",},
    "FLO_16": {"ItemA": "Stomp On Ledge",
               "ItemB": "Leftside Vine",
               "RandomBlockItemA": "In SuperBlock",},
    "FLO_17": {"HiddenYBlockA": "Hidden Block",
               "ItemA": "In The Flowers",},
    "FLO_19": {"ItemA": "On Cloud",},
    "FLO_22": {"ItemA": "Well Reward",},
    "FLO_23": {"HiddenYBlockA": "Upper Hidden Block",
               "HiddenYBlockB": "Lower Hidden Block",},
    "FLO_24": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",
               "Tree1_Drop1A": "In Tree 1",
               "Tree1_Drop1B": "In Tree 2",
               "YBlockA": "Yellow Block",},
    "FLO_25": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Central Vine",
               "Tree1_Drop1A": "In Tree 1",
               "Tree1_Drop1B": "In Tree 2",},

# Shiver Mountain
    "SAM_01": {"ChestA": "Chest In House",
               "GiftA": "Mayor Penguin Gift",
               "GiftB": "Mayor Penguin Letter Reward",
               "HiddenPanel": "Hidden Panel",},
    "SAM_02": {"ItemA": "Toad House Breakfast",
               "ItemB": "Snowmen Gift 1",
               "ItemC": "Snowmen Gift 2",
               "ItemD": "Snowmen Gift 3",
               "ItemE": "Snowmen Gift 4",
               "ItemF": "Snowmen Gift 5",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "SAM_04": {"HiddenPanel": "Hidden Panel",
               "Tree2_Drop1": "In Tree Left",
               "ItemA": "Behind Tree Right",},
    "SAM_05": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Behind Icicle",
               "HiddenYBlockA": "Hidden Block"},
    "SAM_06": {"GiftA": "Merle Gift",
               "GiftB": "Frost T. Letter Reward",},
    "SAM_07": {"HiddenYBlockA": "Hidden Block",},
    "SAM_08": {"ItemA": "Bottom Path",
               "RandomBlockItemA": "In SuperBlock"},
    "SAM_09": {"ItemA": "Socket 1",
               "ItemB": "Socket 2",
               "ItemC": "Socket 3"},
    "SAM_10": {"ItemA": "Left Ledge",
               "RBlockA": "Red Block",},
    "SAM_11": {"ItemA": "In Frozen Pond",},
    "SAM_12": {"ItemA": "On Pedestal",},

# Crystal Palace
    "PRA_04": {"YBlockA": "Yellow Block",},
    "PRA_05": {"ChestA": "In Chest",},
    "PRA_06": {"ItemA": "On The Ground",},
    "PRA_11": {"ChestA": "In Chest",},
    "PRA_12": {"ChestA": "In Chest",},
    "PRA_14": {"RandomBlockItemA": "In MultiCoinBlock Front",
               "RandomBlockItemB": "In MultiCoinBlock Back",},
    "PRA_15": {"ItemA": "On The Ground",},
    "PRA_21": {"HiddenPanel": "Hidden Panel",
               "YBlockA": "Yellow Block",},
    "PRA_22": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",},
    "PRA_27": {"ChestA": "In Chest",},
    "PRA_28": {"ChestA": "In Chest",},
    "PRA_35": {"ChestA": "In Chest",},

# Bowser's Castle
    "KPA_01": {"YBlockA": "Yellow Block",},
    "KPA_03": {"YBlockA": "Yellow Block",},
    "KPA_10": {"YBlockA": "Yellow Block",},
    "KPA_11": {"ItemA": "Defeat Koopatrol Reward",},
    "KPA_14": {"ItemA": "On Island 1",
               "ItemB": "On Island 2",},
    "KPA_15": {"ChestA": "In Chest",},
    "KPA_17": {"CrateA": "In Crate 1",
               "CrateB": "In Crate 2",},
    "KPA_61": {"ItemA": "On Ledge",
               "YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Center",
               "YBlockC": "Yellow Block Right",},
    "KPA_62": {"RBlockA": "Red Block",},
    "KPA_91": {"ItemA": "Defeat Koopatrol Reward",},
    "KPA_95": {"ItemA": "Defeat Koopatrol Reward",},
    "KPA_96": {"ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "KPA_100":{"ItemA": "On The Ground",},
    "KPA_101":{"ItemA": "On The Ground",},
    "KPA_111":{"HiddenYBlockA": "Hidden Block",
               "YBlockA": "Yellow Block",},
    "KPA_119":{"ItemA": "On The Ground",},
    "KPA_133":{"ItemA": "Top Left Ledge",},
    "KPA_134":{"HiddenYBlockA": "Hidden Block",},

# Peach's Castle Grounds
    "OSR_01": {"GiftA": "Muss T. Letter Reward",},
    "OSR_02": {"HiddenYBlockA": "Hidden Block",},
}
