verbose_item_names = {
    "BootsProxy1": "ProgressiveBoots",
    "BootsProxy2": "ProgressiveBoots",
    "BootsProxy3": "ProgressiveBoots",
    "HammerProxy1": "ProgressiveHammer",
    "HammerProxy2": "ProgressiveHammer",
    "HammerProxy3": "ProgressiveHammer",
    "JellyShroom1": "JellyShroom",
    "Letter01": "Letter (To Merlon)",
    "Letter02": "Letter (To Goompa)",
    "Letter03": "Letter (To Mort T.)",
    "Letter04": "Letter (To Russ T.)",
    "Letter05": "Letter (To Mayor Penguin)",
    "Letter06": "Letter (To Merlow)",
    "Letter07": "Letter (To Fice T.)",
    "Letter08": "Letter (To Nomadimouse)",
    "Letter09": "Letter (To Minh T.)",
    "Letter10": "Letter (To Goompapa)",
    "Letter11": "Letter (To Igor)",
    "Letter12": "Letter (To Franky)",
    "Letter13": "Letter (To Muss T.)",
    "Letter14": "Letter (To Koover)",
    "Letter15": "Letter (To Fishmael)",
    "Letter16": "Letter (To Koover)",
    "Letter17": "Letter (To Mr. E.)",
    "Letter18": "Letter (To Miss T.)",
    "Letter19": "Letter (To Little Mouser)",
    "Letter20": "Letter (To Dane T.)",
    "Letter21": "Letter (To Red Yoshi Kid)",
    "Letter22": "Letter (To Dane T.)",
    "Letter23": "Letter (To Frost T.)",
    "Letter24": "Letter (To Goompapa)",
    "Letter25": "Letter (To Kolorado)",
    "BowserCastleKeyA": "BowserCastleKey",
    "BowserCastleKeyB": "BowserCastleKey",
    "BowserCastleKeyC": "BowserCastleKey",
    "BowserCastleKeyD": "BowserCastleKey",
    "BowserCastleKeyE": "BowserCastleKey",
    "KoopaFortressKeyA": "KoopaFortressKey",
    "KoopaFortressKeyB": "KoopaFortressKey",
    "KoopaFortressKeyC": "KoopaFortressKey",
    "KoopaFortressKeyD": "KoopaFortressKey",
    "RuinsKeyA": "RuinsKey",
    "RuinsKeyB": "RuinsKey",
    "RuinsKeyC": "RuinsKey",
    "RuinsKeyD": "RuinsKey",
    "TubbaCastleKeyA": "TubbaCastleKey",
    "TubbaCastleKeyB": "TubbaCastleKey",
    "TubbaCastleKeyC": "TubbaCastleKey",
    "PrisonKeyA": "PrisonKey",
    "PrisonKeyB": "PrisonKey",
    "DamageDodgeA": "DamageDodge",
    "DamageDodgeB": "DamageDodge",
    "DamageDodgeX": "DamageDodge",
    "EarthquakeJump": "QuakeBounce",
    "DeepFocus1": "DeepFocus",
    "DeepFocus2": "DeepFocus",
    "DeepFocus3": "DeepFocus",
    "DefendPlusA": "DefendPlus",
    "DefendPlusX": "DefendPlus",
    "DefendPlusY": "DefendPlus",
    "FlowerSaverA": "FlowerSaver",
    "FlowerSaverB": "FlowerSaver",
    "FlowerSaverX": "FlowerSaver",
    "FPPlusA": "FPPlus",
    "FPPlusB": "FPPlus",
    "FPPlusC": "FPPlus",
    "FPPlusX": "FPPlus",
    "FPPlusY": "FPPlus",
    "HappyFlowerA": "HappyFlower",
    "HappyFlowerB": "HappyFlower",
    "HappyFlowerX": "HappyFlower",
    "HappyHeartA": "HappyHeart",
    "HappyHeartB": "HappyHeart",
    "HappyHeartX": "HappyHeart",
    "HPPlusA": "HPPlus",
    "HPPlusB": "HPPlus",
    "HPPlusC": "HPPlus",
    "HPPlusX": "HPPlus",
    "HPPlusY": "HPPlus",
    "PowerPlusA": "PowerPlus",
    "PowerPlusB": "PowerPlus",
    "PowerPlusX": "PowerPlus",
    "PowerSmash1": "PowerSmash",
    "SmashCharge0": "MiniSmashCharge",
    "JumpCharge0": "MiniJumpCharge",
    "SJumpChg": "SJumpCharge",
    "AutoMultibounce": "Autobounce",
    "SmashChargeProxy1": "ProgressiveSmashCharge",
    "SmashChargeProxy2": "ProgressiveSmashCharge",
    "SmashChargeProxy3": "ProgressiveSmashCharge",
    "JumpChargeProxy1": "ProgressiveJumpCharge",
    "JumpChargeProxy2": "ProgressiveJumpCharge",
    "JumpChargeProxy3": "ProgressiveJumpCharge",
    "PowerJumpProxy1": "ProgressivePowerJump",
    "PowerJumpProxy2": "ProgressivePowerJump",
    "PowerJumpProxy3": "ProgressivePowerJump",
    "PowerSmashProxy1": "ProgressivePowerSmash",
    "PowerSmashProxy2": "ProgressivePowerSmash",
    "PowerSmashProxy3": "ProgressivePowerSmash",
    "QuakeHammerProxy1": "ProgressiveQuakeHammer",
    "QuakeHammerProxy2": "ProgressiveQuakeHammer",
    "QuakeHammerProxy3": "ProgressiveQuakeHammer",
    "CakeProxy": "Cake",
    "BlueBerryProxy1": "BlueBerry",
    "BlueBerryProxy2": "BlueBerry",
    "RedBerryProxy1": "RedBerry",
    "RedBerryProxy2": "RedBerry",
    "YellowBerryProxy1": "YellowBerry",
    "YellowBerryProxy2": "YellowBerry",
    "BubbleBerryProxy1": "BubbleBerry",
    "BubbleBerryProxy2": "BubbleBerry",
    "StarPiece00": "Starpiece",
    "StarPiece01": "Starpiece",
    "StarPiece02": "Starpiece",
    "StarPiece03": "Starpiece",
    "StarPiece04": "Starpiece",
    "StarPiece05": "Starpiece",
    "StarPiece06": "Starpiece",
    "StarPiece07": "Starpiece",
    "StarPiece08": "Starpiece",
    "StarPiece09": "Starpiece",
    "StarPiece0A": "Starpiece",
    "StarPiece0B": "Starpiece",
    "StarPiece0C": "Starpiece",
    "StarPiece0D": "Starpiece",
    "StarPiece0E": "Starpiece",
    "StarPiece0F": "Starpiece",
    "StarPiece10": "Starpiece",
    "StarPiece11": "Starpiece",
    "StarPiece12": "Starpiece",
    "StarPiece13": "Starpiece",
    "StarPiece14": "Starpiece",
    "StarPiece15": "Starpiece",
    "StarPiece16": "Starpiece",
    "StarPiece17": "Starpiece",
    "StarPiece18": "Starpiece",
    "StarPiece19": "Starpiece",
    "StarPiece1A": "Starpiece",
    "StarPiece1B": "Starpiece",
    "StarPiece1C": "Starpiece",
    "StarPiece1D": "Starpiece",
    "StarPiece1E": "Starpiece",
    "StarPiece1F": "Starpiece",
    "StarPiece20": "Starpiece",
    "StarPiece21": "Starpiece",
    "StarPiece22": "Starpiece",
    "StarPiece23": "Starpiece",
    "StarPiece24": "Starpiece",
    "StarPiece25": "Starpiece",
    "StarPiece26": "Starpiece",
    "StarPiece27": "Starpiece",
    "StarPiece28": "Starpiece",
    "StarPiece29": "Starpiece",
    "StarPiece2A": "Starpiece",
    "StarPiece2B": "Starpiece",
    "StarPiece2C": "Starpiece",
    "StarPiece2D": "Starpiece",
    "StarPiece2E": "Starpiece",
    "StarPiece2F": "Starpiece",
    "StarPiece30": "Starpiece",
    "StarPiece31": "Starpiece",
    "StarPiece32": "Starpiece",
    "StarPiece33": "Starpiece",
    "StarPiece34": "Starpiece",
    "StarPiece35": "Starpiece",
    "StarPiece36": "Starpiece",
    "StarPiece37": "Starpiece",
    "StarPiece38": "Starpiece",
    "StarPiece39": "Starpiece",
    "StarPiece3A": "Starpiece",
    "StarPiece3B": "Starpiece",
    "StarPiece3C": "Starpiece",
    "StarPiece3D": "Starpiece",
    "StarPiece3E": "Starpiece",
    "StarPiece3F": "Starpiece",
    "StarPiece40": "Starpiece",
    "StarPiece41": "Starpiece",
    "StarPiece42": "Starpiece",
    "StarPiece43": "Starpiece",
    "StarPiece44": "Starpiece",
    "StarPiece45": "Starpiece",
    "StarPiece46": "Starpiece",
    "StarPiece47": "Starpiece",
    "StarPiece48": "Starpiece",
    "StarPiece49": "Starpiece",
    "StarPiece4A": "Starpiece",
    "StarPiece4B": "Starpiece",
    "StarPiece4C": "Starpiece",
    "StarPiece4D": "Starpiece",
    "StarPiece4E": "Starpiece",
    "StarPiece4F": "Starpiece",
    "StarPiece50": "Starpiece",
    "StarPiece51": "Starpiece",
    "ThreeStarPieces0": "ThreeStarPieces",
    "ThreeStarPieces1": "ThreeStarPieces",
    "ThreeStarPieces2": "ThreeStarPieces",
    "ThreeStarPieces3": "ThreeStarPieces",
    "ThreeStarPieces4": "ThreeStarPieces",
    "PowerStar00": "PowerStar",
    "PowerStar01": "PowerStar",
    "PowerStar02": "PowerStar",
    "PowerStar03": "PowerStar",
    "PowerStar04": "PowerStar",
    "PowerStar05": "PowerStar",
    "PowerStar06": "PowerStar",
    "PowerStar07": "PowerStar",
    "PowerStar08": "PowerStar",
    "PowerStar09": "PowerStar",
    "PowerStar0A": "PowerStar",
    "PowerStar0B": "PowerStar",
    "PowerStar0C": "PowerStar",
    "PowerStar0D": "PowerStar",
    "PowerStar0E": "PowerStar",
    "PowerStar0F": "PowerStar",
    "PowerStar10": "PowerStar",
    "PowerStar11": "PowerStar",
    "PowerStar12": "PowerStar",
    "PowerStar13": "PowerStar",
    "PowerStar14": "PowerStar",
    "PowerStar15": "PowerStar",
    "PowerStar16": "PowerStar",
    "PowerStar17": "PowerStar",
    "PowerStar18": "PowerStar",
    "PowerStar19": "PowerStar",
    "PowerStar1A": "PowerStar",
    "PowerStar1B": "PowerStar",
    "PowerStar1C": "PowerStar",
    "PowerStar1D": "PowerStar",
    "PowerStar1E": "PowerStar",
    "PowerStar1F": "PowerStar",
    "PowerStar20": "PowerStar",
    "PowerStar21": "PowerStar",
    "PowerStar22": "PowerStar",
    "PowerStar23": "PowerStar",
    "PowerStar24": "PowerStar",
    "PowerStar25": "PowerStar",
    "PowerStar26": "PowerStar",
    "PowerStar27": "PowerStar",
    "PowerStar28": "PowerStar",
    "PowerStar29": "PowerStar",
    "PowerStar2A": "PowerStar",
    "PowerStar2B": "PowerStar",
    "PowerStar2C": "PowerStar",
    "PowerStar2D": "PowerStar",
    "PowerStar2E": "PowerStar",
    "PowerStar2F": "PowerStar",
    "PowerStar30": "PowerStar",
    "PowerStar31": "PowerStar",
    "PowerStar32": "PowerStar",
    "PowerStar33": "PowerStar",
    "PowerStar34": "PowerStar",
    "PowerStar35": "PowerStar",
    "PowerStar36": "PowerStar",
    "PowerStar37": "PowerStar",
    "PowerStar38": "PowerStar",
    "PowerStar39": "PowerStar",
    "PowerStar3A": "PowerStar",
    "PowerStar3B": "PowerStar",
    "PowerStar3C": "PowerStar",
    "PowerStar3D": "PowerStar",
    "PowerStar3E": "PowerStar",
    "PowerStar3F": "PowerStar",
    "PowerStar40": "PowerStar",
    "PowerStar41": "PowerStar",
    "PowerStar42": "PowerStar",
    "PowerStar43": "PowerStar",
    "PowerStar44": "PowerStar",
    "PowerStar45": "PowerStar",
    "PowerStar46": "PowerStar",
    "PowerStar47": "PowerStar",
    "PowerStar48": "PowerStar",
    "PowerStar49": "PowerStar",
    "PowerStar4A": "PowerStar",
    "PowerStar4B": "PowerStar",
    "PowerStar4C": "PowerStar",
    "PowerStar4D": "PowerStar",
    "PowerStar4E": "PowerStar",
    "PowerStar4F": "PowerStar",
    "PowerStar50": "PowerStar",
    "PowerStar51": "PowerStar",
    "PowerStar52": "PowerStar",
    "PowerStar53": "PowerStar",
    "PowerStar54": "PowerStar",
    "PowerStar55": "PowerStar",
    "PowerStar56": "PowerStar",
    "PowerStar57": "PowerStar",
    "PowerStar58": "PowerStar",
    "PowerStar59": "PowerStar",
    "PowerStar5A": "PowerStar",
    "PowerStar5B": "PowerStar",
    "PowerStar5C": "PowerStar",
    "PowerStar5D": "PowerStar",
    "PowerStar5E": "PowerStar",
    "PowerStar5F": "PowerStar",
    "PowerStar60": "PowerStar",
    "PowerStar61": "PowerStar",
    "PowerStar62": "PowerStar",
    "PowerStar63": "PowerStar",
    "PowerStar64": "PowerStar",
    "PowerStar65": "PowerStar",
    "PowerStar66": "PowerStar",
    "PowerStar67": "PowerStar",
    "PowerStar68": "PowerStar",
    "PowerStar69": "PowerStar",
    "PowerStar6A": "PowerStar",
    "PowerStar6B": "PowerStar",
    "PowerStar6C": "PowerStar",
    "PowerStar6D": "PowerStar",
    "PowerStar6E": "PowerStar",
    "PowerStar6F": "PowerStar",
    "PowerStar70": "PowerStar",
    "PowerStar71": "PowerStar",
    "PowerStar72": "PowerStar",
    "PowerStar73": "PowerStar",
    "PowerStar74": "PowerStar",
    "PowerStar75": "PowerStar",
    "PowerStar76": "PowerStar",
    "PowerStar77": "PowerStar",
    "PowerStar78": "PowerStar",
    "PowerStar79": "PowerStar",
    "PowerStar7A": "PowerStar",
    "PowerStar7B": "PowerStar",
    "PowerStar7C": "PowerStar",
    "PowerStar7D": "PowerStar",
    "PowerStar7E": "PowerStar",
    "PowerStar7F": "PowerStar",
    "PouchA": "ItemPouch",
    "PouchB": "ItemPouch",
    "PouchC": "ItemPouch",
    "PouchD": "ItemPouch",
    "PouchE": "ItemPouch",
    "GoombarioUp1": "Goombario Upgrade",
    "KooperUp1": "Kooper Upgrade",
    "BombetteUp1": "Bombette Upgrade",
    "ParakarryUp1": "Parakarry Upgrade",
    "WattUp1": "Watt Upgrade",
    "SushieUp1": "Sushie Upgrade",
    "LakilesterUp1": "Lakilester Upgrade",
    "BowUp1": "Bow Upgrade",
    "GoombarioUp2": "Goombario Upgrade",
    "KooperUp2": "Kooper Upgrade",
    "BombetteUp2": "Bombette Upgrade",
    "ParakarryUp2": "Parakarry Upgrade",
    "WattUp2": "Watt Upgrade",
    "SushieUp2": "Sushie Upgrade",
    "LakilesterUp2": "Lakilester Upgrade",
    "BowUp2": "Bow Upgrade",
}
