verbose_item_names = {
    "BootsProxy1": "ProgressiveBoots",
    "BootsProxy2": "ProgressiveBoots",
    "BootsProxy3": "ProgressiveBoots",
    "HammerProxy1": "ProgressiveHammer",
    "HammerProxy2": "ProgressiveHammer",
    "HammerProxy3": "ProgressiveHammer",
    "JellyShroom1": "JellyShroom",
    "Letter01": "Letter (To Merlon)",
    "Letter02": "Letter (To Goompa)",
    "Letter03": "Letter (To Mort T.)",
    "Letter04": "Letter (To Russ T.)",
    "Letter05": "Letter (To Mayor Penguin)",
    "Letter06": "Letter (To Merlow)",
    "Letter07": "Letter (To Fice T.)",
    "Letter08": "Letter (To Nomadimouse)",
    "Letter09": "Letter (To Minh T.)",
    "Letter10": "Letter (To Goompapa) 1",
    "Letter11": "Letter (To Igor)",
    "Letter12": "Letter (To Franky)",
    "Letter13": "Letter (To Muss T.)",
    "Letter14": "Letter (To Koover) 1",
    "Letter15": "Letter (To Fishmael)",
    "Letter16": "Letter (To Koover) 2",
    "Letter17": "Letter (To Mr. E.)",
    "Letter18": "Letter (To Miss T.)",
    "Letter19": "Letter (To Little Mouser)",
    "Letter20": "Letter (To Dane T.)",
    "Letter21": "Letter (To Red Yoshi Kid)",
    "Letter22": "Letter (To Dane T.)",
    "Letter23": "Letter (To Frost T.)",
    "Letter24": "Letter (To Goompapa) 2",
    "Letter25": "Letter (To Kolorado)",
    "BowserCastleKeyA": "BowserCastleKey",
    "BowserCastleKeyB": "BowserCastleKey",
    "BowserCastleKeyC": "BowserCastleKey",
    "BowserCastleKeyD": "BowserCastleKey",
    "BowserCastleKeyE": "BowserCastleKey",
    "KoopaFortressKeyA": "KoopaFortressKey",
    "KoopaFortressKeyB": "KoopaFortressKey",
    "KoopaFortressKeyC": "KoopaFortressKey",
    "KoopaFortressKeyD": "KoopaFortressKey",
    "RuinsKeyA": "RuinsKey",
    "RuinsKeyB": "RuinsKey",
    "RuinsKeyC": "RuinsKey",
    "RuinsKeyD": "RuinsKey",
    "TubbaCastleKeyA": "TubbaCastleKey",
    "TubbaCastleKeyB": "TubbaCastleKey",
    "TubbaCastleKeyC": "TubbaCastleKey",
    "PrisonKeyA": "PrisonKey",
    "PrisonKeyB": "PrisonKey",
    "DamageDodgeA": "DamageDodge",
    "DamageDodgeB": "DamageDodge",
    "DamageDodgeX": "DamageDodge",
    "EarthquakeJump": "QuakeBounce",
    "DeepFocus1": "DeepFocus",
    "DeepFocus2": "DeepFocus",
    "DeepFocus3": "DeepFocus",
    "DefendPlusA": "DefendPlus",
    "DefendPlusX": "DefendPlus",
    "DefendPlusY": "DefendPlus",
    "FlowerSaverA": "FlowerSaver",
    "FlowerSaverB": "FlowerSaver",
    "FlowerSaverX": "FlowerSaver",
    "FPPlusA": "FPPlus",
    "FPPlusB": "FPPlus",
    "FPPlusC": "FPPlus",
    "FPPlusX": "FPPlus",
    "FPPlusY": "FPPlus",
    "HappyFlowerA": "HappyFlower",
    "HappyFlowerB": "HappyFlower",
    "HappyFlowerX": "HappyFlower",
    "HappyHeartA": "HappyHeart",
    "HappyHeartB": "HappyHeart",
    "HappyHeartX": "HappyHeart",
    "HPPlusA": "HPPlus",
    "HPPlusB": "HPPlus",
    "HPPlusC": "HPPlus",
    "HPPlusX": "HPPlus",
    "HPPlusY": "HPPlus",
    "PowerPlusA": "PowerPlus",
    "PowerPlusB": "PowerPlus",
    "PowerPlusX": "PowerPlus",
    "PowerSmash1": "PowerSmash",
    "SmashCharge0": "MiniSmashCharge",
    "SSmashChg": "SSmashCharge",
    "JumpCharge0": "MiniJumpCharge",
    "SJumpChg": "SJumpCharge",
    "AutoMultibounce": "Autobounce",
    "SmashChargeProxy1": "ProgressiveSmashCharge",
    "SmashChargeProxy2": "ProgressiveSmashCharge",
    "SmashChargeProxy3": "ProgressiveSmashCharge",
    "JumpChargeProxy1": "ProgressiveJumpCharge",
    "JumpChargeProxy2": "ProgressiveJumpCharge",
    "JumpChargeProxy3": "ProgressiveJumpCharge",
    "PowerJumpProxy1": "ProgressivePowerJump",
    "PowerJumpProxy2": "ProgressivePowerJump",
    "PowerJumpProxy3": "ProgressivePowerJump",
    "PowerSmashProxy1": "ProgressivePowerSmash",
    "PowerSmashProxy2": "ProgressivePowerSmash",
    "PowerSmashProxy3": "ProgressivePowerSmash",
    "QuakeHammerProxy1": "ProgressiveQuakeHammer",
    "QuakeHammerProxy2": "ProgressiveQuakeHammer",
    "QuakeHammerProxy3": "ProgressiveQuakeHammer",
    "StarPiece00": "StarPiece",
    "StarPiece01": "StarPiece",
    "StarPiece02": "StarPiece",
    "StarPiece03": "StarPiece",
    "StarPiece04": "StarPiece",
    "StarPiece05": "StarPiece",
    "StarPiece06": "StarPiece",
    "StarPiece07": "StarPiece",
    "StarPiece08": "StarPiece",
    "StarPiece09": "StarPiece",
    "StarPiece0A": "StarPiece",
    "StarPiece0B": "StarPiece",
    "StarPiece0C": "StarPiece",
    "StarPiece0D": "StarPiece",
    "StarPiece0E": "StarPiece",
    "StarPiece0F": "StarPiece",
    "StarPiece10": "StarPiece",
    "StarPiece11": "StarPiece",
    "StarPiece12": "StarPiece",
    "StarPiece13": "StarPiece",
    "StarPiece14": "StarPiece",
    "StarPiece15": "StarPiece",
    "StarPiece16": "StarPiece",
    "StarPiece17": "StarPiece",
    "StarPiece18": "StarPiece",
    "StarPiece19": "StarPiece",
    "StarPiece1A": "StarPiece",
    "StarPiece1B": "StarPiece",
    "StarPiece1C": "StarPiece",
    "StarPiece1D": "StarPiece",
    "StarPiece1E": "StarPiece",
    "StarPiece1F": "StarPiece",
    "StarPiece20": "StarPiece",
    "StarPiece21": "StarPiece",
    "StarPiece22": "StarPiece",
    "StarPiece23": "StarPiece",
    "StarPiece24": "StarPiece",
    "StarPiece25": "StarPiece",
    "StarPiece26": "StarPiece",
    "StarPiece27": "StarPiece",
    "StarPiece28": "StarPiece",
    "StarPiece29": "StarPiece",
    "StarPiece2A": "StarPiece",
    "StarPiece2B": "StarPiece",
    "StarPiece2C": "StarPiece",
    "StarPiece2D": "StarPiece",
    "StarPiece2E": "StarPiece",
    "StarPiece2F": "StarPiece",
    "StarPiece30": "StarPiece",
    "StarPiece31": "StarPiece",
    "StarPiece32": "StarPiece",
    "StarPiece33": "StarPiece",
    "StarPiece34": "StarPiece",
    "StarPiece35": "StarPiece",
    "StarPiece36": "StarPiece",
    "StarPiece37": "StarPiece",
    "StarPiece38": "StarPiece",
    "StarPiece39": "StarPiece",
    "StarPiece3A": "StarPiece",
    "StarPiece3B": "StarPiece",
    "StarPiece3C": "StarPiece",
    "StarPiece3D": "StarPiece",
    "StarPiece3E": "StarPiece",
    "StarPiece3F": "StarPiece",
    "StarPiece40": "StarPiece",
    "StarPiece41": "StarPiece",
    "StarPiece42": "StarPiece",
    "StarPiece43": "StarPiece",
    "StarPiece44": "StarPiece",
    "StarPiece45": "StarPiece",
    "StarPiece46": "StarPiece",
    "StarPiece47": "StarPiece",
    "StarPiece48": "StarPiece",
    "StarPiece49": "StarPiece",
    "StarPiece4A": "StarPiece",
    "StarPiece4B": "StarPiece",
    "StarPiece4C": "StarPiece",
    "StarPiece4D": "StarPiece",
    "StarPiece4E": "StarPiece",
    "StarPiece4F": "StarPiece",
    "StarPiece50": "StarPiece",
    "StarPiece51": "StarPiece",
    "ThreeStarPieces0": "ThreeStarPieces",
    "ThreeStarPieces1": "ThreeStarPieces",
    "ThreeStarPieces2": "ThreeStarPieces",
    "ThreeStarPieces3": "ThreeStarPieces",
    "ThreeStarPieces4": "ThreeStarPieces",
    "PowerStar00": "PowerStar",
    "PowerStar01": "PowerStar",
    "PowerStar02": "PowerStar",
    "PowerStar03": "PowerStar",
    "PowerStar04": "PowerStar",
    "PowerStar05": "PowerStar",
    "PowerStar06": "PowerStar",
    "PowerStar07": "PowerStar",
    "PowerStar08": "PowerStar",
    "PowerStar09": "PowerStar",
    "PowerStar0A": "PowerStar",
    "PowerStar0B": "PowerStar",
    "PowerStar0C": "PowerStar",
    "PowerStar0D": "PowerStar",
    "PowerStar0E": "PowerStar",
    "PowerStar0F": "PowerStar",
    "PowerStar10": "PowerStar",
    "PowerStar11": "PowerStar",
    "PowerStar12": "PowerStar",
    "PowerStar13": "PowerStar",
    "PowerStar14": "PowerStar",
    "PowerStar15": "PowerStar",
    "PowerStar16": "PowerStar",
    "PowerStar17": "PowerStar",
    "PowerStar18": "PowerStar",
    "PowerStar19": "PowerStar",
    "PowerStar1A": "PowerStar",
    "PowerStar1B": "PowerStar",
    "PowerStar1C": "PowerStar",
    "PowerStar1D": "PowerStar",
    "PowerStar1E": "PowerStar",
    "PowerStar1F": "PowerStar",
    "PowerStar20": "PowerStar",
    "PowerStar21": "PowerStar",
    "PowerStar22": "PowerStar",
    "PowerStar23": "PowerStar",
    "PowerStar24": "PowerStar",
    "PowerStar25": "PowerStar",
    "PowerStar26": "PowerStar",
    "PowerStar27": "PowerStar",
    "PowerStar28": "PowerStar",
    "PowerStar29": "PowerStar",
    "PowerStar2A": "PowerStar",
    "PowerStar2B": "PowerStar",
    "PowerStar2C": "PowerStar",
    "PowerStar2D": "PowerStar",
    "PowerStar2E": "PowerStar",
    "PowerStar2F": "PowerStar",
    "PowerStar30": "PowerStar",
    "PowerStar31": "PowerStar",
    "PowerStar32": "PowerStar",
    "PowerStar33": "PowerStar",
    "PowerStar34": "PowerStar",
    "PowerStar35": "PowerStar",
    "PowerStar36": "PowerStar",
    "PowerStar37": "PowerStar",
    "PowerStar38": "PowerStar",
    "PowerStar39": "PowerStar",
    "PowerStar3A": "PowerStar",
    "PowerStar3B": "PowerStar",
    "PowerStar3C": "PowerStar",
    "PowerStar3D": "PowerStar",
    "PowerStar3E": "PowerStar",
    "PowerStar3F": "PowerStar",
    "PowerStar40": "PowerStar",
    "PowerStar41": "PowerStar",
    "PowerStar42": "PowerStar",
    "PowerStar43": "PowerStar",
    "PowerStar44": "PowerStar",
    "PowerStar45": "PowerStar",
    "PowerStar46": "PowerStar",
    "PowerStar47": "PowerStar",
    "PowerStar48": "PowerStar",
    "PowerStar49": "PowerStar",
    "PowerStar4A": "PowerStar",
    "PowerStar4B": "PowerStar",
    "PowerStar4C": "PowerStar",
    "PowerStar4D": "PowerStar",
    "PowerStar4E": "PowerStar",
    "PowerStar4F": "PowerStar",
    "PowerStar50": "PowerStar",
    "PowerStar51": "PowerStar",
    "PowerStar52": "PowerStar",
    "PowerStar53": "PowerStar",
    "PowerStar54": "PowerStar",
    "PowerStar55": "PowerStar",
    "PowerStar56": "PowerStar",
    "PowerStar57": "PowerStar",
    "PowerStar58": "PowerStar",
    "PowerStar59": "PowerStar",
    "PowerStar5A": "PowerStar",
    "PowerStar5B": "PowerStar",
    "PowerStar5C": "PowerStar",
    "PowerStar5D": "PowerStar",
    "PowerStar5E": "PowerStar",
    "PowerStar5F": "PowerStar",
    "PowerStar60": "PowerStar",
    "PowerStar61": "PowerStar",
    "PowerStar62": "PowerStar",
    "PowerStar63": "PowerStar",
    "PowerStar64": "PowerStar",
    "PowerStar65": "PowerStar",
    "PowerStar66": "PowerStar",
    "PowerStar67": "PowerStar",
    "PowerStar68": "PowerStar",
    "PowerStar69": "PowerStar",
    "PowerStar6A": "PowerStar",
    "PowerStar6B": "PowerStar",
    "PowerStar6C": "PowerStar",
    "PowerStar6D": "PowerStar",
    "PowerStar6E": "PowerStar",
    "PowerStar6F": "PowerStar",
    "PowerStar70": "PowerStar",
    "PowerStar71": "PowerStar",
    "PowerStar72": "PowerStar",
    "PowerStar73": "PowerStar",
    "PowerStar74": "PowerStar",
    "PowerStar75": "PowerStar",
    "PowerStar76": "PowerStar",
    "PowerStar77": "PowerStar",
    "PowerStar78": "PowerStar",
    "PowerStar79": "PowerStar",
    "PowerStar7A": "PowerStar",
    "PowerStar7B": "PowerStar",
    "PowerStar7C": "PowerStar",
    "PowerStar7D": "PowerStar",
    "PowerStar7E": "PowerStar",
    "PowerStar7F": "PowerStar",
    "PouchA": "ItemPouch",
    "PouchB": "ItemPouch",
    "PouchC": "ItemPouch",
    "PouchD": "ItemPouch",
    "PouchE": "ItemPouch",
    "GenericUpgrade": "SuperBlock",
    "GoombarioUp1": "GoombarioUpgrade",
    "KooperUp1": "KooperUpgrade",
    "BombetteUp1": "BombetteUpgrade",
    "ParakarryUp1": "ParakarryUpgrade",
    "WattUp1": "WattUpgrade",
    "SushieUp1": "SushieUpgrade",
    "LakilesterUp1": "LakilesterUpgrade",
    "BowUp1": "BowUpgrade",
    "GoombarioUp2": "GoombarioUpgrade",
    "KooperUp2": "KooperUpgrade",
    "BombetteUp2": "BombetteUpgrade",
    "ParakarryUp2": "ParakarryUpgrade",
    "WattUp2": "WattUpgrade",
    "SushieUp2": "SushieUpgrade",
    "LakilesterUp2": "LakilesterUpgrade",
    "BowUp2": "BowUpgrade",
}

inverted_verbose_names = {
    "ProgressiveBoots": [
        "BootsProxy1",
        "BootsProxy2",
        "BootsProxy3",
    ],
    "ProgressiveHammer": [
        "HammerProxy1",
        "HammerProxy2",
        "HammerProxy3",
    ],
    "JellyShroom": "JellyShroom1",
    "Letter (To Merlon)": "Letter01",
    "Letter (To Goompa)": "Letter02",
    "Letter (To Mort T.)": "Letter03",
    "Letter (To Russ T.)": "Letter04",
    "Letter (To Mayor Penguin)": "Letter05",
    "Letter (To Merlow)": "Letter06",
    "Letter (To Fice T.)": "Letter07",
    "Letter (To Nomadimouse)": "Letter08",
    "Letter (To Minh T.)": "Letter09",
    "Letter (To Goompapa) 1": "Letter10",
    "Letter (To Igor)": "Letter11",
    "Letter (To Franky)": "Letter12",
    "Letter (To Muss T.)": "Letter13",
    "Letter (To Koover) 1": "Letter14",
    "Letter (To Fishmael)": "Letter15",
    "Letter (To Koover) 2": "Letter16",
    "Letter (To Mr. E.)": "Letter17",
    "Letter (To Miss T.)": "Letter18",
    "Letter (To Little Mouser)": "Letter19",
    "Letter (To Dane T.) 1": "Letter20",
    "Letter (To Red Yoshi Kid)": "Letter21",
    "Letter (To Dane T.) 2": "Letter22",
    "Letter (To Frost T.)": "Letter23",
    "Letter (To Goompapa) 2": "Letter24",
    "Letter (To Kolorado)": "Letter25",
    "BowserCastleKey": [
        "BowserCastleKeyA",
        "BowserCastleKeyB",
        "BowserCastleKeyC",
        "BowserCastleKeyD",
        "BowserCastleKeyE",
    ],
    "KoopaFortressKey": [
        "KoopaFortressKeyA",
        "KoopaFortressKeyB",
        "KoopaFortressKeyC",
        "KoopaFortressKeyD",
    ],
    "RuinsKey": [
        "RuinsKeyA",
        "RuinsKeyB",
        "RuinsKeyC",
        "RuinsKeyD",
    ],
    "TubbaCastleKey": [
        "TubbaCastleKeyA",
        "TubbaCastleKeyB",
        "TubbaCastleKeyC",
    ],
    "PrisonKey": [
        "PrisonKeyA",
        "PrisonKeyB",
    ],
    "DamageDodge": [
        "DamageDodgeA",
        "DamageDodgeB",
        "DamageDodgeX",
    ],
    "QuakeBounce": "EarthquakeJump",
    "DeepFocus": [
        "DeepFocus1",
        "DeepFocus2",
        "DeepFocus3",
    ],
    "DefendPlus": [
        "DefendPlusA",
        "DefendPlusX",
        "DefendPlusY",
    ],
    "FlowerSaver": [
        "FlowerSaverA",
        "FlowerSaverB",
        "FlowerSaverX",
    ],
    "FPPlus": [
        "FPPlusA",
        "FPPlusB",
        "FPPlusC",
        "FPPlusX",
        "FPPlusY",
    ],
    "HappyFlower": [
        "HappyFlowerA",
        "HappyFlowerB",
        "HappyFlowerX",
    ],
    "HappyHeart": [
        "HappyHeartA",
        "HappyHeartB",
        "HappyHeartX",
    ],
    "HPPlus": [
        "HPPlusA",
        "HPPlusB",
        "HPPlusC",
        "HPPlusX",
        "HPPlusY",
    ],
    "PowerPlus": [
        "PowerPlusA",
        "PowerPlusB",
        "PowerPlusX",
    ],
    "PowerSmash": "PowerSmash1",
    "MiniSmashCharge": "SmashCharge0",
    "SSmashCharge": "SSmashChg",
    "MiniJumpCharge": "JumpCharge0",
    "SJumpCharge": "SJumpChg",
    "Autobounce": "AutoMultibounce",
    "ProgressiveSmashCharge": [
        "SmashChargeProxy1",
        "SmashChargeProxy2",
        "SmashChargeProxy3",
    ],
    "ProgressiveJumpCharge": [
        "JumpChargeProxy1",
        "JumpChargeProxy2",
        "JumpChargeProxy3",
    ],
    "ProgressivePowerJump": [
        "PowerJumpProxy1",
        "PowerJumpProxy2",
        "PowerJumpProxy3",
    ],
    "ProgressivePowerSmash": [
        "PowerSmashProxy1",
        "PowerSmashProxy2",
        "PowerSmashProxy3",
    ],
    "ProgressiveQuakeHammer": [
        "QuakeHammerProxy1",
        "QuakeHammerProxy2",
        "QuakeHammerProxy3",
    ],
    "StarPiece": [
        "StarPiece00",
        "StarPiece01",
        "StarPiece02",
        "StarPiece03",
        "StarPiece04",
        "StarPiece05",
        "StarPiece06",
        "StarPiece07",
        "StarPiece08",
        "StarPiece09",
        "StarPiece0A",
        "StarPiece0B",
        "StarPiece0C",
        "StarPiece0D",
        "StarPiece0E",
        "StarPiece0F",
        "StarPiece10",
        "StarPiece11",
        "StarPiece12",
        "StarPiece13",
        "StarPiece14",
        "StarPiece15",
        "StarPiece16",
        "StarPiece17",
        "StarPiece18",
        "StarPiece19",
        "StarPiece1A",
        "StarPiece1B",
        "StarPiece1C",
        "StarPiece1D",
        "StarPiece1E",
        "StarPiece1F",
        "StarPiece20",
        "StarPiece21",
        "StarPiece22",
        "StarPiece23",
        "StarPiece24",
        "StarPiece25",
        "StarPiece26",
        "StarPiece27",
        "StarPiece28",
        "StarPiece29",
        "StarPiece2A",
        "StarPiece2B",
        "StarPiece2C",
        "StarPiece2D",
        "StarPiece2E",
        "StarPiece2F",
        "StarPiece30",
        "StarPiece31",
        "StarPiece32",
        "StarPiece33",
        "StarPiece34",
        "StarPiece35",
        "StarPiece36",
        "StarPiece37",
        "StarPiece38",
        "StarPiece39",
        "StarPiece3A",
        "StarPiece3B",
        "StarPiece3C",
        "StarPiece3D",
        "StarPiece3E",
        "StarPiece3F",
        "StarPiece40",
        "StarPiece41",
        "StarPiece42",
        "StarPiece43",
        "StarPiece44",
        "StarPiece45",
        "StarPiece46",
        "StarPiece47",
        "StarPiece48",
        "StarPiece49",
        "StarPiece4A",
        "StarPiece4B",
        "StarPiece4C",
        "StarPiece4D",
        "StarPiece4E",
        "StarPiece4F",
        "StarPiece50",
        "StarPiece51",
    ],
    "ThreeStarPieces": [
        "ThreeStarPieces0",
        "ThreeStarPieces1",
        "ThreeStarPieces2",
        "ThreeStarPieces3",
        "ThreeStarPieces4",
    ],
    "PowerStar": [
        "PowerStar00",
        "PowerStar01",
        "PowerStar02",
        "PowerStar03",
        "PowerStar04",
        "PowerStar05",
        "PowerStar06",
        "PowerStar07",
        "PowerStar08",
        "PowerStar09",
        "PowerStar0A",
        "PowerStar0B",
        "PowerStar0C",
        "PowerStar0D",
        "PowerStar0E",
        "PowerStar0F",
        "PowerStar10",
        "PowerStar11",
        "PowerStar12",
        "PowerStar13",
        "PowerStar14",
        "PowerStar15",
        "PowerStar16",
        "PowerStar17",
        "PowerStar18",
        "PowerStar19",
        "PowerStar1A",
        "PowerStar1B",
        "PowerStar1C",
        "PowerStar1D",
        "PowerStar1E",
        "PowerStar1F",
        "PowerStar20",
        "PowerStar21",
        "PowerStar22",
        "PowerStar23",
        "PowerStar24",
        "PowerStar25",
        "PowerStar26",
        "PowerStar27",
        "PowerStar28",
        "PowerStar29",
        "PowerStar2A",
        "PowerStar2B",
        "PowerStar2C",
        "PowerStar2D",
        "PowerStar2E",
        "PowerStar2F",
        "PowerStar30",
        "PowerStar31",
        "PowerStar32",
        "PowerStar33",
        "PowerStar34",
        "PowerStar35",
        "PowerStar36",
        "PowerStar37",
        "PowerStar38",
        "PowerStar39",
        "PowerStar3A",
        "PowerStar3B",
        "PowerStar3C",
        "PowerStar3D",
        "PowerStar3E",
        "PowerStar3F",
        "PowerStar40",
        "PowerStar41",
        "PowerStar42",
        "PowerStar43",
        "PowerStar44",
        "PowerStar45",
        "PowerStar46",
        "PowerStar47",
        "PowerStar48",
        "PowerStar49",
        "PowerStar4A",
        "PowerStar4B",
        "PowerStar4C",
        "PowerStar4D",
        "PowerStar4E",
        "PowerStar4F",
        "PowerStar50",
        "PowerStar51",
        "PowerStar52",
        "PowerStar53",
        "PowerStar54",
        "PowerStar55",
        "PowerStar56",
        "PowerStar57",
        "PowerStar58",
        "PowerStar59",
        "PowerStar5A",
        "PowerStar5B",
        "PowerStar5C",
        "PowerStar5D",
        "PowerStar5E",
        "PowerStar5F",
        "PowerStar60",
        "PowerStar61",
        "PowerStar62",
        "PowerStar63",
        "PowerStar64",
        "PowerStar65",
        "PowerStar66",
        "PowerStar67",
        "PowerStar68",
        "PowerStar69",
        "PowerStar6A",
        "PowerStar6B",
        "PowerStar6C",
        "PowerStar6D",
        "PowerStar6E",
        "PowerStar6F",
        "PowerStar70",
        "PowerStar71",
        "PowerStar72",
        "PowerStar73",
        "PowerStar74",
        "PowerStar75",
        "PowerStar76",
        "PowerStar77",
        "PowerStar78",
        "PowerStar79",
        "PowerStar7A",
        "PowerStar7B",
        "PowerStar7C",
        "PowerStar7D",
        "PowerStar7E",
        "PowerStar7F",
    ],
    "ItemPouch": [
        "PouchA",
        "PouchB",
        "PouchC",
        "PouchD",
        "PouchE",
    ],
    "GoombarioUpgrade": [
        "GoombarioUp1",
        "GoombarioUp2",
    ],
    "KooperUpgrade": [
        "KooperUp1",
        "KooperUp2",
    ],
    "BombetteUpgrade": [
        "BombetteUp1",
        "BombetteUp2",
    ],
    "ParakarryUpgrade": [
        "ParakarryUp1",
        "ParakarryUp2",
    ],
    "BowUpgrade": [
        "BowUp1",
        "BowUp2",
    ],
    "WattUpgrade": [
        "WattUp1",
        "WattUp2",
    ],
    "SushieUpgrade": [
        "SushieUp1",
        "SushieUp2",
    ],
    "LakilesterUpgrade": [
        "LakilesterUp1",
        "LakilesterUp2",
    ],
}
