verbose_area_names = {
    "KMR": "Goomba Region",
    "MAC": "Toad Town",
    "TIK": "Toad Town Tunnels",
    "KGR": "Inside the Whale",
    "KKJ": "Peach's Castle",
    "HOS": "Shooting Star Summit",
    "NOK": "Koopa Region",
    "TRD": "Koopa Bros Fortress",
    "IWA": "Mt Rugged",
    "DRO": "Dry Dry Outpost",
    "SBK": "Dry Dry Desert",
    "ISK": "Dry Dry Ruins",
    "MIM": "Forever Forest",
    "OBK": "Boo's Mansion",
    "ARN": "Gusty Gulch",
    "DGB": "Tubba's Castle",
    "OMO": "Shy Guy's Toybox",
    "JAN": "Jade Jungle",
    "KZN": "Mt Lavalava",
    "FLO": "Flower Fields",
    "SAM": "Shiver Region",
    "PRA": "Crystal Palace",
    "KPA": "Bowser's Castle",
    "OSR": "Peach's Castle Grounds",
}
