replenishing_itemlocations = [
    "DRO_01/ShopItemA","DRO_01/ShopItemC","DRO_01/ShopItemF",
    "FLO_16/ItemB",
    "FLO_09/ItemB",
    "FLO_03/Tree1_Drop1A","FLO_03/Tree1_Drop1B",
    "FLO_08/ItemB","FLO_08/Tree1_Drop1A","FLO_08/Tree1_Drop1B",
    "FLO_24/Tree1_Drop1A","FLO_24/Tree1_Drop1B",
    "FLO_25/ItemA","FLO_25/Tree1_Drop1A","FLO_25/Tree1_Drop1B",
    "FLO_14/ItemB",
    "HOS_03/ShopItemA","HOS_03/ShopItemB","HOS_03/ShopItemC","HOS_03/ShopItemD","HOS_03/ShopItemE","HOS_03/ShopItemF",
    "IWA_10/ItemD",
    "JAN_00/Tree1_Drop1A",
    "JAN_01/ItemD","JAN_01/ItemE","JAN_01/ItemF","JAN_01/ItemG","JAN_01/ItemH","JAN_01/ItemJ",
    "JAN_02/Tree2_Drop1A","JAN_02/Tree3_Drop1A",
    "JAN_03/GiftB","JAN_03/ShopItemA","JAN_03/ShopItemB","JAN_03/ShopItemC","JAN_03/ShopItemD","JAN_03/ShopItemE","JAN_03/ShopItemF",
    "KMR_02/Tree1_Drop1A",
    "KPA_96/ShopItemA","KPA_96/ShopItemB","KPA_96/ShopItemC","KPA_96/ShopItemD","KPA_96/ShopItemE","KPA_96/ShopItemF",
    "MAC_00/ShopItemA","MAC_00/ShopItemB","MAC_00/ShopItemC","MAC_00/ShopItemD","MAC_00/ShopItemE","MAC_00/ShopItemF",
    "MAC_04/ShopItemA","MAC_04/ShopItemB","MAC_04/ShopItemC","MAC_04/ShopItemD","MAC_04/ShopItemE","MAC_04/ShopItemF",
    "MIM_11/ItemA",
    "NOK_01/Bush4_Drop1A","NOK_01/ShopItemA","NOK_01/ShopItemB","NOK_01/ShopItemC","NOK_01/ShopItemD","NOK_01/ShopItemE","NOK_01/ShopItemF",
    "NOK_02/Bush1_Drop1",
    "OBK_03/ShopItemA","OBK_03/ShopItemB","OBK_03/ShopItemC","OBK_03/ShopItemD","OBK_03/ShopItemE","OBK_03/ShopItemF",
    "OBK_05/CrateA","OBK_05/CrateB",
    "OMO_01/ItemB","OMO_01/ItemC","OMO_01/ItemD","OMO_01/ItemE","OMO_01/ItemF",
    "SAM_02/ItemA","SAM_02/ShopItemA","SAM_02/ShopItemB","SAM_02/ShopItemC","SAM_02/ShopItemD","SAM_02/ShopItemE","SAM_02/ShopItemF",
    "SBK_56/Tree1_Drop1A","SBK_56/Tree2_Drop1A",
    "TIK_15/GiftH",
]

# replenishing_locations = {
#     "FLO_16": ["ItemB"],
#     "FLO_09": ["ItemB"],
#     "FLO_03": ["Tree1_Drop1A","Tree1_Drop1B"],
#     "FLO_08": ["ItemB","Tree1_Drop1A","Tree1_Drop1B"],
#     "FLO_24": ["Tree1_Drop1A","Tree1_Drop1B"],
#     "FLO_25": ["ItemA","Tree1_Drop1A","Tree1_Drop1B"],
#     "FLO_14": ["ItemB"],
#     "HOS_03": ["ShopItemA","ShopItemB","ShopItemC","ShopItemD","ShopItemE","ShopItemF"],
#     "IWA_10": ["ItemD"],
#     "JAN_00": ["Tree1_Drop1A"],
#     "JAN_01": ["ItemD","ItemE","ItemF","ItemG","ItemH","ItemJ"],
#     "JAN_02": ["Tree2_Drop1A","Tree3_Drop1A"],
#     "JAN_03": ["GiftB","ShopItemA","ShopItemB","ShopItemC","ShopItemD","ShopItemE","ShopItemF"],
#     "KMR_02": ["Tree1_Drop1A"],
#     "KPA_96": ["ShopItemA","ShopItemB","ShopItemC","ShopItemD","ShopItemE","ShopItemF"],
#     "MAC_00": ["ShopItemA","ShopItemB","ShopItemC","ShopItemD","ShopItemE","ShopItemF"],
#     "MAC_04": ["ShopItemA","ShopItemB","ShopItemC","ShopItemD","ShopItemE","ShopItemF"],
#     "MIM_11": ["ItemA"],
#     "NOK_01": ["Bush4_Drop1A","ShopItemA","ShopItemB","ShopItemC","ShopItemD","ShopItemE","ShopItemF"],
#     "NOK_02": ["Bush1_Drop1"],
#     "OBK_03": ["ShopItemA","ShopItemB","ShopItemC","ShopItemD","ShopItemE","ShopItemF"],
#     "OBK_05": ["CrateA","CrateB"],
#     "SAM_02": ["ItemA","ShopItemA","ShopItemB","ShopItemC","ShopItemD","ShopItemE","ShopItemF"],
#     "SBK_56": ["Tree1_Drop1A","Tree2_Drop1A"],
# }