verbose_item_locations = {
# Goomba Region
    "KMR_00": {"HiddenPanel": "Hidden Panel",},
    "KMR_02": {"GiftA": "Goompa Koopa Koot Favor",
               "GiftB": "Goompa Gift",
               "ItemA": "On The Balcony",
               "Tree1_Drop1A": "Goomnut Tree",
               "Partner": "Goombario Partner"},
    "KMR_03": {"ItemA": "Floating Coin 1",
               "ItemB": "Floating Coin 2",
               "ItemC": "Floating Coin 3",
               "ItemD": "Floating Coin 4",
               "ItemE": "Upper Ledge",
               "ItemF": "In Tree",
               "HiddenPanel": "Hidden Panel",
               "YBlockA": "Block On Ground",
               "HiddenYBlockA": "Above Stone Block",},
    "KMR_04": {"ItemA": "In Tree",},
    "KMR_05": {"ItemA": "On Ledge",
               "ItemB": "In Tree"},
    "KMR_06": {"ItemA": "Upper Ledge",
               "RBlockA": "Red Block",},
    "KMR_09": {"YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},
    "KMR_10": {"ChestA": "Chest On Roof",
               "YBlockA": "Yellow Block",},
    "KMR_11": {"HiddenPanel": "Hidden Panel",
               "Tree1_Drop1A": "In Tree",
               "YBlockA": "Hidden Yellow Block",},
    "KMR_20": {"GiftA": "Luigi Koopa Koot Favor",},

# Toad Town
    "MAC_00": {"ItemA": "Sushie Island",
               "HiddenPanel": "Hidden Panel",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",
               "DojoA": "Dojo: Chan",
               "DojoB": "Dojo: Lee",
               "DojoC": "Dojo: Master 1",
               "DojoD": "Dojo: Master 2",
               "DojoE": "Dojo: Master 3",},
    "MAC_01": {"ItemA": "Merlon House Stomping",
               "Tree1_Drop1A": "In Tree",
               "ShopBadgeA": "Rowf's Shop Set 1",
               "ShopBadgeB": "Rowf's Shop Set 1",
               "ShopBadgeC": "Rowf's Shop Set 1",
               "ShopBadgeD": "Rowf's Shop Set 1",
               "ShopBadgeE": "Rowf's Shop Set 2",
               "ShopBadgeF": "Rowf's Shop Set 2",
               "ShopBadgeG": "Rowf's Shop Set 2",
               "ShopBadgeH": "Rowf's Shop Set 3",
               "ShopBadgeI": "Rowf's Shop Set 3",
               "ShopBadgeJ": "Rowf's Shop Set 3",
               "ShopBadgeK": "Rowf's Shop Set 4",
               "ShopBadgeL": "Rowf's Shop Set 4",
               "ShopBadgeM": "Rowf's Shop Set 4",
               "ShopBadgeN": "Rowf's Shop Set 5",
               "ShopBadgeO": "Rowf's Shop Set 5",
               "ShopBadgeP": "Rowf's Shop Set 5",},
    "MAC_02": {"GiftA": "Bub-ulb Gift",
               "GiftB": "Tayce T. Thanks For Pan",
               "ItemA": "Inside Blue House",
               "HiddenPanel": "Hidden Panel",},
    "MAC_03": {"GiftA": "ToadKid Letter Delivery 1",
               "GiftB": "ToadKid Letter Delivery 2",
               "HiddenPanel": "Hidden Panel",},
    "MAC_04": {"ItemA": "Storeroom Item 1",
               "ItemB": "Storeroom Item 2",
               "ItemC": "Storeroom Item 3",
               "ItemD": "Storeroom Item 4",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "MAC_05": {"GiftA": "Poet Gift",
               "GiftB": "Poet Thanks For Melody",
               "HiddenPanel": "Hidden Panel",},

# Toad Town Tunnels
    "TIK_02": {"ChestA": "Blooper Fight Reward"},
    "TIK_03": {"YBlockA": "Yellow Block Center",
               "YBlockB": "Yellow Block Left",
               "YBlockC": "Yellor Block Right",},
    "TIK_05": {"ChestA": "Chest On Ledge"},
    "TIK_07": {"ItemA": "On Parakarry Ledge"},
    "TIK_10": {"HiddenYBlockA": "Hidden Block Left",
               "HiddenYBlockB": "Hidden Block Center",
               "HiddenYBlockC": "Hidden Block Right",},
    "TIK_15": {"GiftA": "Rip Cheato Offer 1",
               "GiftB": "Rip Cheato Offer 2",
               "GiftC": "Rip Cheato Offer 3",
               "GiftD": "Rip Cheato Offer 4",
               "GiftE": "Rip Cheato Offer 5",
               "GiftF": "Rip Cheato Offer 6",
               "GiftG": "Rip Cheato Offer 7",
               "GiftH": "Rip Cheato Offer 8",
               "GiftI": "Rip Cheato Offer 9",
               "GiftJ": "Rip Cheato Offer 10",
               "GiftK": "Rip Cheato Infinite Offer",},
    "TIK_18": {"HiddenYBlockA": "Hidden Block"},
    "TIK_20": {"YBlockA": "Yellow Block"},
    "TIK_21": {"YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "YBlockC": "Yellow Block 3",
               "YBlockD": "Yellow Block 4",
               "YBlockE": "Yellow Block 5",},
    "TIK_23": {"HiddenYBlockA": "Hidden Block Center",
               "HiddenYBlockB": "Hidden Block Right",
               "HiddenYBlockC": "Hidden Block Left",
               "YBlockA": "Yellow Block",},
    "TIK_24": {"HiddenYBlockA": "Hidden Block",
               "YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},

# Peach's Castle
    "KKJ_16": {"ItemA": "Upper Level",
               "ItemB": "Between Bookshelves",},
    "KKJ_17": {"ItemA": "On The Ground"},
    "KKJ_20": {"ChestA": "In Chest"},

# Shooting Star Summit
    "HOS_00": {"HiddenPanel": "Hidden Panel",},
    "HOS_01": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Behind The Summit",},
    "HOS_03": {"ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "HOS_06": {"GiftA": "Merluvlee Koopa Koot Favor",
               "HiddenPanel": "Hidden Panel",
               "ShopBadgeA": "Merlow's Badges 1",
               "ShopBadgeB": "Merlow's Badges 2",
               "ShopBadgeC": "Merlow's Badges 3",
               "ShopBadgeD": "Merlow's Badges 4",
               "ShopBadgeE": "Merlow's Badges 5",
               "ShopBadgeF": "Merlow's Badges 6",
               "ShopBadgeG": "Merlow's Badges 7",
               "ShopBadgeH": "Merlow's Badges 8",
               "ShopBadgeI": "Merlow's Badges 9",
               "ShopBadgeJ": "Merlow's Badges 10",
               "ShopBadgeK": "Merlow's Badges 11",
               "ShopBadgeL": "Merlow's Badges 12",
               "ShopBadgeM": "Merlow's Badges 13",
               "ShopBadgeN": "Merlow's Badges 14",
               "ShopBadgeO": "Merlow's Badges 15",
               },

# Koopa Region
    "NOK_01": {"Bush1_Drop1A": "Coin Bush 1",
               "Bush3_Drop1A": "Bush Left Front",
               "Bush4_Drop1A": "Bush Infront Of Tree",
               "Bush5_Drop1A": "Coin Bush 2",
               "Bush6A_Drop1A": "Bush Second From Right (Koopa Koot Favor)",
               "Bush7A_Drop1A": "Bush Far Right (Koopa Koot Favor)",
               "HiddenPanel": "Hidden Panel",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "NOK_02": {"Bush1_Drop1": "Bush Far Left",
               "GiftA": "Kolorado's Wife (Koopa Koot Favor)",
               "GiftB": "Koopa Koot Silver Credit",
               "GiftC": "Koopa Koot Gold Credit",
               "ItemA": "Push Block Puzzle",
               "Partner": "Kooper Partner",
               "KootGift00": "Koopa Koot Reward 1",
               "KootGift01": "Koopa Koot Reward 2",
               "KootGift02": "Koopa Koot Reward 3",
               "KootGift03": "Koopa Koot Reward 4",
               "KootGift04": "Koopa Koot Reward 5",
               "KootGift05": "Koopa Koot Reward 6",
               "KootGift06": "Koopa Koot Reward 7",
               "KootGift07": "Koopa Koot Reward 8",
               "KootGift08": "Koopa Koot Reward 9",
               "KootGift09": "Koopa Koot Reward 10",
               "KootGift0A": "Koopa Koot Reward 11",
               "KootGift0B": "Koopa Koot Reward 12",
               "KootGift0C": "Koopa Koot Reward 13",
               "KootGift0D": "Koopa Koot Reward 14",
               "KootGift0E": "Koopa Koot Reward 15",
               "KootGift0F": "Koopa Koot Reward 16",
               "KootGift10": "Koopa Koot Reward 17",
               "KootGift11": "Koopa Koot Reward 18",
               "KootGift12": "Koopa Koot Reward 19",
               "KootGift13": "Koopa Koot Reward 20",},
    "NOK_03": {"ItemA": "On Stump",},
    "NOK_04": {"GiftA": "Fuzzy Battle Reward",},
    "NOK_11": {"RBlockA": "Red Block Center",
               "YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},
    "NOK_12": {"ItemA": "Kooper Island",
               "ItemB": "Behind Fence",
               "YBlockA": "Yellow Block",},
    "NOK_13": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Behind Peg",
               "RBlockA": "Brick Block Puzzle",},
    "NOK_14": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",
               "ItemA": "X On Ground 1",
               "ItemB": "X On Ground 2",
               "ItemC": "X On Ground 3",
               "ItemD": "X On Ground 4",
               "ItemE": "X On Ground 5",
               "ItemF": "On Brick Block",},
    "NOK_15": {"Tree1_Drop1A": "In Tree",},

# Koopa Bros. Fortress
    "TRD_00": {"ChestA": "Chest Behind Fortress",
               "ChestB": "Chest On Ledge",},
    "TRD_01": {"ItemA": "Top Of Tower",
               "ItemB": "Koopa Troopa Reward",},
    "TRD_03": {"ItemA": "Left Cell",
               "ItemB": "Right Cell",
               "ItemC": "Center Cell",},
    "TRD_06": {"Partner": "Bombette Partner"},
    "TRD_08": {"ItemA": "On The Ground",},
    "TRD_09": {"YBlockA": "Block Behind Rock",},

# Mt Rugged
    "IWA_00": {"ItemA": "On Slide 1",
               "ItemB": "On Slide 2",
               "ItemC": "On Slide 3",
               "ItemD": "Hurting Whacka",
               "YBlockA": "Yellow Block",},
    "IWA_01": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Parakarry Ledge",
               "ItemB": "Kooper Ledge",},
    "IWA_02": {"GiftA": "Bub-ulb Gift",
               "ItemA": "On Scaffolding",},
    "IWA_03": {"ChestA": "Hidden Cave Chest",
               "ItemA": "Slide Ledge",
               "ItemB": "Left Ledge Center",
               "ItemC": "Left Ledge Right",
               "ItemD": "Left Ledge 3",
               "ItemE": "Left Ledge 4",
               "ItemF": "Left Ledge 5",
               "ItemG": "Left Ledge 6",
               "ItemH": "Left Ledge 7",
               "ItemI": "Bottom Left 1",
               "ItemJ": "Bottom Left 2",
               "YBlockA": "Yellow Block Top Left",
               "YBlockB": "Yellow Block Floating",
               "YBlockC": "Yellow Block Top Right",},
    "IWA_04": {"ItemA": "Bottom Of Cliff",},
    "IWA_10": {"ItemA": "Bush 1",
               "ItemB": "Bush 2",
               "ItemC": "Bush 3",
               "ItemD": "Bush Top",
               "Partner": "Parakarry Partner"},

# Dry Dry Outpost
    "DRO_01": {"GiftA": "Composer For Lyrics",
               "GiftB": "Store Legend",
               "ShopItemA": "Shop Item 1",
               "ShopItemC": "Shop Item 3",
               "ShopItemF": "Shop Item 6",},
    "DRO_02": {"GiftA": "Merlee Request (Koopa Koot Favor)",
               "GiftB": "Moustafa Gift",
               "HiddenPanel": "Hidden Panel",
               "ItemA": "Mr. E. Letter Delivery",},

# Dry Dry Desert
    "SBK_00": {"YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},
    "SBK_05": {"ItemA": "Behind Cactus",},
    "SBK_10": {"HiddenYBlockA": "Hidden Block",},
    "SBK_14": {"YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},
    "SBK_20": {"YBlockA": "Hit Block",
               "YBlockB": "Hit Block Plenty",
               "YBlockC": "Hit Block Very Much",},
    "SBK_22": {"YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "YBlockC": "Yellow Block 3",
               "YBlockD": "Yellow Block 4",
               "YBlockE": "Yellow Block Center",},
    "SBK_24": {"HiddenRBlockA": "Hidden Block",},
    "SBK_30": {"Tree2_Drop1A": "In Tree",},
    "SBK_33": {"HiddenPanel": "Hidden Panel",},
    "SBK_36": {"Tree9_Drop1A": "In Tree (Top Right)",},
    "SBK_43": {"YBlockA": "Yellow Block",},
    "SBK_45": {"ItemA": "On Brick Block",
               "ItemB": "Ontop Of Bluffs",},
    "SBK_46": {"HiddenYBlockA": "Hidden Block",
               "YBlockA": "Yellow Block",},
    "SBK_55": {"ItemA": "Behind Bush",},
    "SBK_56": {"Tree1_Drop1A": "In Tree (Left)",
               "Tree2_Drop1A": "In Tree (Right)",},
    "SBK_61": {"HiddenRBlockA": "Hidden Block",},
    "SBK_64": {"YBlockA": "Yellow Block",},

# Dry Dry Ruins
    "ISK_02": {"ItemA": "In Sarcophagus",},
    "ISK_03": {"ItemA": "On The Ground",},
    "ISK_05": {"ItemA": "On Pedestal",},
    "ISK_06": {"ItemA": "In The Sand",
               "ItemB": "On Ledge",},
    "ISK_07": {"ItemA": "Pokey Gauntlet Reward",
               "ItemB": "Behind Hammer Block",},
    "ISK_09": {"ChestA": "Hidden Chest",},
    "ISK_12": {"ItemA": "On Ledge",},
    "ISK_13": {"ItemA": "On Pedestal",},
    "ISK_14": {"ItemA": "On Pedestal",},

# Forever Forest
    "MIM_04": {"GiftA": "Bub-ulb Gift",},
    "MIM_08": {"RBlockA": "Central Block",},
    "MIM_09": {"RBlockA": "Central Block",},
    "MIM_11": {"ItemA": "In Bush (Back Right)",
               "YBlockA": "Yellow Block",},
    "MIM_12": {"HiddenPanel": "Hidden Panel",},

# Boo's Mansion
    "OBK_01": {"GiftA": "From Boo (Koopa Koot Favor)",
               "HiddenPanel": "Hidden Panel",},
    "OBK_02": {"HiddenPanel": "Hidden Panel",},
    "OBK_03": {"CrateA": "In Crate",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "OBK_04": {"CrateA": "In Crate",
               "HiddenPanel": "Hidden Panel",},
    "OBK_05": {"CrateA": "In Crate 1",
               "CrateB": "In Crate 2",},
    "OBK_06": {"CrateA": "In Crate",
               "ItemA": "On Bookshelf",},
    "OBK_07": {"ChestA": "In Chest",},
    "OBK_08": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Beat Boo Game",},
    "OBK_09": {"Partner": "Bow Partner"},

# Gusty Gulch
    "ARN_02": {"ItemA": "On Rock",
               "ItemB": "Infront Of Branch",
               "YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "YBlockC": "Yellow Block Right",},
    "ARN_03": {"GiftA": "From Boo (Koopa Koot Favor)",
               "YBlockA": "Yellow Block In House",},
    "ARN_04": {"ItemA": "Behind Rock",
               "YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},

# Tubba's Castle
    "DGB_03": {"ItemA": "On Table",},
    "DGB_06": {"ChestA": "In Chest",},
    "DGB_07": {"ItemA": "On Table",},
    "DGB_11": {"ItemA": "On Table",},
    "DGB_12": {"ChestA": "In Chest",},
    "DGB_13": {"ItemA": "In Hidden Room",
               "ItemB": "On Bed 1",
               "ItemC": "On Bed 2",
               "ItemD": "On Bed 3",
               "ItemE": "On Bed 4",
               "ItemF": "On Bed 5",
               "ItemG": "On Bed 6",},
    "DGB_14": {"YBlockA": "Yellow Block",},
    "DGB_16": {"ItemA": "On Pedestal",},

# Shy Guy's Toybox
    "OMO_01": {"HiddenYBlockA": "Hidden Block 1",
               "HiddenYBlockB": "Hidden Block 2",
               "ItemA": "Calculator Thief 1",
               "ItemB": "Calculator Thief 2",
               "ItemC": "Shy Guy 2",
               "ItemD": "Shy Guy 3",
               "ItemE": "Shy Guy 4",
               "ItemF": "Shy Guy 5",},
    "OMO_02": {"HiddenYBlockA": "Hidden Block Left",
               "ItemA": "On Brick Block",
               "YBlockA": "Hidden Block Right",},
    "OMO_03": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",},
    "OMO_04": {"ChestA": "In Chest",
               "ItemA": "Infront Of Chest",
               "ItemB": "Midair 1",
               "ItemC": "Midair 2",
               "ItemD": "Midair 3",
               "ItemE": "Midair 4",
               "ItemF": "Midair 5",
               "ItemG": "Midair 6",
               "ItemH": "Midair 7",
               "ItemI": "Midair 8",
               "ItemJ": "On Building",
               "ItemK": "Behind Building Block",
               "YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "YBlockC": "Yellow Block On Ledge",},
    "OMO_05": {"HiddenYBlockA": "Hidden Block Right",
               "HiddenYBlockB": "Hidden Block Left",
               "ItemA": "Gourmet Guy Reward",
               "YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",},
    "OMO_06": {"ChestA": "In Chest",
               "HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",},
    "OMO_07": {"ChestA": "In Chest (Far Right)",
               "ChestB": "In Chest (Top Left)",
               "ChestC": "In Chest (Right)",
               "ItemA": "Infront Of Chest (Right)",
               "YBlockA": "Yellow Block",},
    "OMO_08": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",},
    "OMO_09": {"ChestA": "In Chest",
               "ItemA": "Infront Of Chest",
               "ItemB": "On Treadmill 1",
               "ItemC": "On Treadmill 2",
               "ItemD": "On Treadmill 3",
               "ItemE": "On Treadmill 4",
               "ItemF": "On Treadmill 5",
               "ItemG": "On Treadmill 6",
               "ItemH": "Hidden Room Center",
               "ItemI": "Hidden Room 1",
               "ItemJ": "Hidden Room 2",
               "ItemK": "Hidden Room 3",
               "ItemL": "Hidden Room 4",
               "ItemM": "Hidden Room 5",
               "ItemN": "Hidden Room 6",
               "ItemO": "Defeat Shy Guy",},
    "OMO_10": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",},
    "OMO_11": {"HiddenRBlockA": "Hidden Block Center",
               "HiddenYBlockA": "Hidden Block Right",
               "HiddenYBlockB": "Hidden Block Left",
               "YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",},
    "OMO_12": {"Partner": "Watt Partner"},
    "OMO_13": {"ChestA": "In Chest",
               "HiddenYBlockA": "Hidden Block",
               "YBlockA": "Yellow Block",},
    "OMO_17": {"YBlockA": "Yellow Block South",
               "YBlockB": "Yellow Block North 1",
               "YBlockC": "Yellow Block North 2",},

# Jade Jungle
    "JAN_00": {"ItemA": "Over Flower 1",
               "ItemB": "Over Flower 2",
               "ItemC": "Behind Bush",
               "Tree1_Drop1A": "In Palm Tree",},
    "JAN_01": {"HiddenYBlockA": "Hidden Block Left",
               "HiddenYBlockB": "Hidden Block Right",
               "ItemA": "On The Rocks",
               "ItemB": "Over Flower 1",
               "ItemC": "Over Flower 2",
               "ItemD": "In Palm Tree 1",
               "ItemE": "In Palm Tree 2",
               "ItemF": "In Palm Tree 3",
               "ItemG": "In Palm Tree 4",
               "ItemH": "In Palm Tree 5",
               "ItemI": "In Palm Tree 5.2",
               "ItemJ": "In Palm Tree 6",},
    "JAN_02": {"GiftA": "Village Leader Reward",
               "HiddenPanel": "Hidden Panel",
               "Tree2_Drop1A": "In Palm Tree Left",
               "Tree3_Drop1A": "In Palm Tree Right",},
    "JAN_03": {"GiftA": "Kolorado Volcano Vase Reward",
               "GiftB": "Cooked Goods Fan Yoshi",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "JAN_04": {"ChestA": "In Volcano Chest",
               "ItemA": "On Island",
               "Tree2_Drop1A": "In Island Tree",
               "Partner": "Sushie Partner",},
    "JAN_05": {"RBlockA": "Red Block",},
    "JAN_06": {"ItemA": "Underwater",},
    "JAN_08": {"HiddenYBlockA": "Hidden Block",
               "ItemA": "Underwater 1",
               "ItemB": "Underwater 2",
               "ItemC": "Underwater 3",},
    "JAN_09": {"ItemA": "Bush 1",
               "ItemB": "Bush 1",
               "ItemC": "Bush 2",
               "ItemD": "In Tree",},
    "JAN_10": {"ItemA": "Underwater",},
    "JAN_12": {"HiddenYBlockA": "Hidden Block",
               "ItemA": "In Tree",},
    "JAN_13": {"HiddenYBlockA": "Hidden Block",},
    "JAN_14": {"ItemA": "Tree Vine Second Left",
               "ItemB": "Tree Vine Far Right",},
    "JAN_15": {"HiddenPanel": "Hidden Panel",},
    "JAN_18": {"ItemA": "End Of Vine",},
    "JAN_22": {"GiftA": "Raphael Gift",
               "ItemA": "Behind Tree",},

# Mt Lavalava
    "KZN_03": {"ItemA": "On Stone Pillar",
               "ItemB": "On Brick Block",
               "YBlockA": "Yellow Block 1",
               "YBlockB": "Yellow Block 2",
               "YBlockC": "Yellow Block 3",
               "YBlockD": "Yellow Block 4",},
    "KZN_06": {"HiddenYBlockA": "Hidden Block",},
    "KZN_08": {"ChestA": "In Chest",},
    "KZN_09": {"HiddenPanel": "Hidden Panel",},
    "KZN_18": {"HiddenPanel": "Hidden Panel",},
    "KZN_19": {"YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Right",},

# Flower Fields
    "FLO_03": {"GiftA": "Petunia Gift",
               "HiddenPanel": "Hidden Panel",
               "Tree1_Drop1A": "In Tree 1",
               "Tree1_Drop1B": "In Tree 2",},
    "FLO_07": {"GiftA": "Posie Gift 1",
               "ItemA": "Posie Gift 2",},
    "FLO_08": {"ItemA": "Left Side Vine",
               "ItemB": "In The Flowers",
               "Tree1_Drop1A": "In Tree 1",
               "Tree1_Drop1B": "In Tree 2",},
    "FLO_09": {"ItemA": "Tree Puzzle Reward",
               "ItemB": "Leftmost Vine",},
    "FLO_10": {"GiftA": "Lily Reward For WaterStone",
               "Tree1_Drop1A": "In Tree",},
    "FLO_12": {"GiftA": "Rosie Gift",},
    "FLO_13": {"ItemA": "Cage Under Rock",
               "ItemB": "In The Flowers",
               "Partner": "Lakilester Partner",},
    "FLO_14": {"ItemA": "On Ledge",
               "ItemB": "Left Vine",},
    "FLO_16": {"ItemA": "Stomp On Ledge",
               "ItemB": "Leftside Vine",},
    "FLO_17": {"HiddenYBlockA": "Hidden Block",
               "ItemA": "In The Flowers",},
    "FLO_19": {"ItemA": "On Cloud",},
    "FLO_22": {"ItemA": "Well Reward",},
    "FLO_23": {"HiddenYBlockA": "Lower Hidden Block",
               "HiddenYBlockB": "Upper Hidden Block",},
    "FLO_24": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",
               "Tree1_Drop1A": "In Tree 1",
               "Tree1_Drop1B": "In Tree 2",
               "YBlockA": "Yellow Block",},
    "FLO_25": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Central Vine",
               "Tree1_Drop1A": "In Tree 1",
               "Tree1_Drop1B": "In Tree 2",},

# Shiver Mountain
    "SAM_01": {"ChestA": "Chest In House",
               "GiftA": "Mayor Gift",
               "HiddenPanel": "Hidden Panel",},
    "SAM_02": {"ItemA": "Toad House Breakfast",
               "ItemB": "Snowmen Gift 1",
               "ItemC": "Snowmen Gift 2",
               "ItemD": "Snowmen Gift 3",
               "ItemE": "Snowmen Gift 4",
               "ItemF": "Snowmen Gift 5",
               "ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "SAM_04": {"HiddenPanel": "Hidden Panel",
               "ItemA": "In Tree Left",
               "ItemB": "In Tree Right",},
    "SAM_05": {"HiddenPanel": "Hidden Panel",
               "ItemA": "Behind Icicle",
               "HiddenYBlockA": "Hidden Block"},
    "SAM_06": {"GiftA": "Merle Gift",},
    "SAM_07": {"HiddenYBlockA": "Hidden Block",},
    "SAM_08": {"ItemA": "Bottom Path",},
    "SAM_09": {"ItemA": "Socket 1",
               "ItemB": "Socket 2",
               "ItemC": "Socket 3"},
    "SAM_10": {"ItemA": "Left Ledge",
               "RBlockA": "Red Block",},
    "SAM_11": {"ItemA": "In Frozen Pond",},
    "SAM_12": {"ItemA": "On Pedestal",},

# Crystal Palace
    "PRA_04": {"YBlockA": "Yellow Block",},
    "PRA_05": {"ChestA": "In Chest",},
    "PRA_06": {"ItemA": "On The Ground",},
    "PRA_11": {"ChestA": "In Chest",},
    "PRA_12": {"ChestA": "In Chest",},
    "PRA_15": {"ItemA": "On The Ground",},
    "PRA_21": {"HiddenPanel": "Hidden Panel",
               "YBlockA": "Yellow Block",},
    "PRA_22": {"HiddenPanel": "Hidden Panel",
               "HiddenYBlockA": "Hidden Block",},
    "PRA_27": {"ChestA": "In Chest",},
    "PRA_28": {"ChestA": "In Chest",},
    "PRA_35": {"ChestA": "In Chest",},

# Bowser's Castle
    "KPA_01": {"YBlockA": "Yellow Block",},
    "KPA_03": {"YBlockA": "Yellow Block",},
    "KPA_10": {"YBlockA": "Yellow Block",},
    "KPA_11": {"ItemA": "Defeat Koopatrol Reward",},
    "KPA_14": {"ItemA": "On Island 1",
               "ItemB": "On Island 2",},
    "KPA_15": {"ChestA": "In Chest",},
    "KPA_17": {"CrateA": "In Crate 1",
               "CrateB": "In Crate 2",},
    "KPA_61": {"ItemA": "On Ledge",
               "YBlockA": "Yellow Block Left",
               "YBlockB": "Yellow Block Center",
               "YBlockC": "Yellow Block Right",},
    "KPA_62": {"RBlockA": "Red Block",},
    "KPA_91": {"ItemA": "Defeat Koopatrol Reward",},
    "KPA_95": {"ItemA": "Defeat Koopatrol Reward",},
    "KPA_96": {"ShopItemA": "Shop Item 1",
               "ShopItemB": "Shop Item 2",
               "ShopItemC": "Shop Item 3",
               "ShopItemD": "Shop Item 4",
               "ShopItemE": "Shop Item 5",
               "ShopItemF": "Shop Item 6",},
    "KPA_100":{"ItemA": "On The Ground",},
    "KPA_101":{"ItemA": "On The Ground",},
    "KPA_111":{"HiddenYBlockA": "Hidden Block",
               "YBlockA": "Yellow Block",},
    "KPA_119":{"ItemA": "On The Ground",},
    "KPA_133":{"ItemA": "Top Left Ledge",},
    "KPA_134":{"HiddenYBlockA": "Hidden Block",},

# Peach's Castle Grounds
    "OSR_02": {"HiddenYBlockA": "Hidden Block",},
}
