verbose_item_names = {
    "Letter01": "Letter (To Merlon)",
    "Letter02": "Letter (To Goompa)",
    "Letter03": "Letter (To Mort T.)",
    "Letter04": "Letter (To Russ T.)",
    "Letter05": "Letter (To Mayor Penguin)",
    "Letter06": "Letter (To Merlow)",
    "Letter07": "Letter (To Fice T.)",
    "Letter08": "Letter (To Nomadimouse)",
    "Letter09": "Letter (To Minh T.)",
    "Letter10": "Letter (To Goompapa)",
    "Letter11": "Letter (To Franky)",
    "Letter12": "Letter (To Franky)",
    "Letter13": "Letter (To Muss T.)",
    "Letter14": "Letter (To Koover)",
    "Letter15": "Letter (To Fishmael)",
    "Letter16": "Letter (To Koover)",
    "Letter17": "Letter (To Mr. E.)",
    "Letter18": "Letter (To Miss T.)",
    "Letter19": "Letter (To Little Mouser)",
    "Letter20": "Letter (To Dane T.)",
    "Letter21": "Letter (To Red Yoshi Kid)",
    "Letter22": "Letter (To Dane T.)",
    "Letter23": "Letter (To Frost T.)",
    "Letter24": "Letter (To Goompapa)",
    "Letter25": "Letter (To Kolorado)",
    "BowserCastleKeyA": "BowserCastleKey",
    "BowserCastleKeyB": "BowserCastleKey",
    "BowserCastleKeyC": "BowserCastleKey",
    "BowserCastleKeyD": "BowserCastleKey",
    "BowserCastleKeyE": "BowserCastleKey",
    "KoopaFortressKeyA": "KoopaFortressKey",
    "KoopaFortressKeyB": "KoopaFortressKey",
    "KoopaFortressKeyC": "KoopaFortressKey",
    "KoopaFortressKeyD": "KoopaFortressKey",
    "RuinsKeyA": "RuinsKey",
    "RuinsKeyB": "RuinsKey",
    "RuinsKeyC": "RuinsKey",
    "RuinsKeyD": "RuinsKey",
    "TubbaCastleKeyA": "TubbaCastleKey",
    "TubbaCastleKeyB": "TubbaCastleKey",
    "TubbaCastleKeyC": "TubbaCastleKey",
    "PrisonKeyA": "PrisonKey",
    "PrisonKeyB": "PrisonKey",
    "DamageDodgeA": "DamageDodge",
    "DamageDodgeB": "DamageDodge",
    "DeepFocus1": "DeepFocus",
    "DeepFocus2": "DeepFocus",
    "DeepFocus3": "DeepFocus",
    "DefendPlusA": "DefendPlus",
    "FlowerSaverA": "FlowerSaver",
    "FlowerSaverB": "FlowerSaver",
    "FPPlusA": "FPPlus",
    "FPPlusB": "FPPlus",
    "HappyFlowerA": "HappyFlower",
    "HappyFlowerB": "HappyFlower",
    "HappyHeartA": "HappyHeart",
    "HappyHeartB": "HappyHeart",
    "HPPlusA": "HPPlus",
    "HPPlusB": "HPPlus",
    "HPPlusC": "HPPlus",
    "PowerPlusA": "PowerPlus",
    "PowerPlusB": "PowerPlus",
    "PowerSmash1": "PowerSmash",
    "SJumpChg": "SJumpCharge",
    "StarPiece00": "Starpiece",
    "StarPiece01": "Starpiece",
    "StarPiece02": "Starpiece",
    "StarPiece03": "Starpiece",
    "StarPiece04": "Starpiece",
    "StarPiece05": "Starpiece",
    "StarPiece06": "Starpiece",
    "StarPiece07": "Starpiece",
    "StarPiece08": "Starpiece",
    "StarPiece09": "Starpiece",
    "StarPiece0A": "Starpiece",
    "StarPiece0B": "Starpiece",
    "StarPiece0C": "Starpiece",
    "StarPiece0D": "Starpiece",
    "StarPiece0E": "Starpiece",
    "StarPiece0F": "Starpiece",
    "StarPiece10": "Starpiece",
    "StarPiece11": "Starpiece",
    "StarPiece12": "Starpiece",
    "StarPiece13": "Starpiece",
    "StarPiece14": "Starpiece",
    "StarPiece15": "Starpiece",
    "StarPiece16": "Starpiece",
    "StarPiece17": "Starpiece",
    "StarPiece18": "Starpiece",
    "StarPiece19": "Starpiece",
    "StarPiece1A": "Starpiece",
    "StarPiece1B": "Starpiece",
    "StarPiece1C": "Starpiece",
    "StarPiece1D": "Starpiece",
    "StarPiece1E": "Starpiece",
    "StarPiece1F": "Starpiece",
    "StarPiece20": "Starpiece",
    "StarPiece22": "Starpiece",
    "StarPiece23": "Starpiece",
    "StarPiece24": "Starpiece",
    "StarPiece25": "Starpiece",
    "StarPiece26": "Starpiece",
    "StarPiece27": "Starpiece",
    "StarPiece28": "Starpiece",
    "StarPiece29": "Starpiece",
    "StarPiece2A": "Starpiece",
    "StarPiece2B": "Starpiece",
    "StarPiece2C": "Starpiece",
    "StarPiece2D": "Starpiece",
    "StarPiece2E": "Starpiece",
    "StarPiece2F": "Starpiece",
    "StarPiece30": "Starpiece",
    "StarPiece31": "Starpiece",
    "StarPiece32": "Starpiece",
    "StarPiece33": "Starpiece",
    "StarPiece34": "Starpiece",
    "StarPiece35": "Starpiece",
    "StarPiece36": "Starpiece",
    "StarPiece37": "Starpiece",
    "StarPiece38": "Starpiece",
    "StarPiece39": "Starpiece",
    "StarPiece3A": "Starpiece",
    "StarPiece3B": "Starpiece",
    "StarPiece3C": "Starpiece",
    "StarPiece3D": "Starpiece",
    "StarPiece3E": "Starpiece",
    "StarPiece3F": "Starpiece",
    "StarPiece40": "Starpiece",
    "StarPiece41": "Starpiece",
}
